<template>
    <div class="instructor-insights-dashboard">
      <div class="page-header">
        <h1>Instructor Insights Dashboard</h1>
        <div class="header-actions">
          <button class="btn btn-primary" @click="refreshData">
            <i class="fas fa-sync-alt"></i> Refresh
          </button>
        </div>
      </div>
  
      <!-- Loading State -->
      <div v-if="loading" class="loading-container">
        <div class="spinner-border text-primary" role="status">
          <span class="visually-hidden">Loading...</span>
        </div>
        <p>Analyzing your teaching data...</p>
      </div>
  
      <!-- Error State -->
      <div v-if="error" class="alert alert-danger">
        <strong>Error:</strong> {{ error }}
      </div>
  
      <!-- Dashboard Content -->
      <div v-if="!loading && !error" class="dashboard-content">
        <!-- AI-Generated Narrative Card -->
        <div class="card narrative-card mb-4">
          <div class="card-header d-flex justify-content-between align-items-center">
            <h2 class="m-0">
              <i class="fas fa-robot me-2"></i> AI-Generated Insights
            </h2>
            <span class="badge bg-primary">Generated by Gemini</span>
          </div>
          <div class="card-body">
            <div v-if="insights.narrative" class="narrative-content">
              <p v-for="(paragraph, index) in formattedNarrative" :key="index" class="narrative-paragraph">
                {{ paragraph }}
              </p>
            </div>
            <div v-else class="placeholder-content">
              <p>No narrative available. Try refreshing the data.</p>
            </div>
          </div>
        </div>
  
        <!-- Key Metrics Overview -->
        <div class="row mb-4">
          <div class="col-md-3">
            <div class="card stat-card">
              <div class="card-body">
                <h5 class="card-title">Total Courses</h5>
                <p class="stat-value">{{ insights.dashboard_data?.total_courses || 0 }}</p>
              </div>
            </div>
          </div>
          <div class="col-md-3">
            <div class="card stat-card">
              <div class="card-body">
                <h5 class="card-title">Total Students</h5>
                <p class="stat-value">{{ insights.dashboard_data?.total_students || 0 }}</p>
              </div>
            </div>
          </div>
          <div class="col-md-3">
            <div class="card stat-card">
              <div class="card-body">
                <h5 class="card-title">At-Risk Students</h5>
                <p class="stat-value">{{ insights.dashboard_data?.at_risk_students_count || 0 }}</p>
              </div>
            </div>
          </div>
          <div class="col-md-3">
            <div class="card stat-card">
              <div class="card-body">
                <h5 class="card-title">Avg. Instructor Rating</h5>
                <p class="stat-value">
                  {{ insights.dashboard_data?.overall_metrics?.avg_instructor_rating?.toFixed(1) || 'N/A' }}
                  <small>/5</small>
                </p>
              </div>
            </div>
          </div>
        </div>
  
        <!-- At-Risk Students Section -->
        <div class="card mb-4">
          <div class="card-header">
            <h2>
              <i class="fas fa-exclamation-triangle me-2"></i> At-Risk Students
            </h2>
          </div>
          <div class="card-body">
            <div v-if="insights.dashboard_data?.at_risk_students?.length" class="table-responsive">
              <table class="table table-striped">
                <thead>
                  <tr>
                    <th>Student</th>
                    <th>Risk Score</th>
                    <th>Current Trimester</th>
                    <th>Key Factors</th>
                    <th>Actions</th>
                  </tr>
                </thead>
                <tbody>
                  <tr v-for="student in insights.dashboard_data.at_risk_students" :key="student.student_id">
                    <td>{{ student.name }}</td>
                    <td>
                      <div class="risk-score">
                        <div class="progress" style="height: 10px;">
                          <div
                            class="progress-bar"
                            :class="riskScoreClass(student.risk_score)"
                            role="progressbar"
                            :style="{ width: `${student.risk_score * 100}%` }"
                            :aria-valuenow="student.risk_score * 100"
                            aria-valuemin="0"
                            aria-valuemax="100"
                          ></div>
                        </div>
                        <span>{{ (student.risk_score * 100).toFixed(0) }}%</span>
                      </div>
                    </td>
                    <td>{{ student.current_trimester }}</td>
                    <td>
                      <span
                        v-for="(factor, index) in student.key_factors"
                        :key="index"
                        class="badge bg-warning text-dark me-1"
                      >
                        {{ factor }}
                      </span>
                    </td>
                    <td>
                      <button class="btn btn-sm btn-outline-primary">
                        <i class="fas fa-envelope me-1"></i> Contact
                      </button>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
            <div v-else class="placeholder-content">
              <p>No at-risk students identified at this time.</p>
            </div>
          </div>
        </div>
  
        <!-- Course Performance Overview -->
        <div class="card">
          <div class="card-header">
            <h2>
              <i class="fas fa-book me-2"></i> Course Performance
            </h2>
          </div>
          <div class="card-body">
            <div v-if="Object.keys(insights.dashboard_data?.courses || {}).length" class="table-responsive">
              <table class="table">
                <thead>
                  <tr>
                    <th>Course</th>
                    <th>Pass Rate</th>
                    <th>Avg. Quiz 1</th>
                    <th>Avg. Quiz 2</th>
                    <th>Avg. Endterm</th>
                    <th>Attendance</th>
                    <th>Actions</th>
                  </tr>
                </thead>
                <tbody>
                  <tr v-for="(course, code) in insights.dashboard_data.courses" :key="code">
                    <td>{{ course.course_name }}</td>
                    <td>
                      <span :class="passRateClass(course.pass_rate)">
                        {{ course.pass_rate ? course.pass_rate.toFixed(1) + '%' : 'N/A' }}
                      </span>
                    </td>
                    <td>{{ course.avg_quiz1 ? course.avg_quiz1.toFixed(1) : 'N/A' }}</td>
                    <td>{{ course.avg_quiz2 ? course.avg_quiz2.toFixed(1) : 'N/A' }}</td>
                    <td>{{ course.avg_endterm ? course.avg_endterm.toFixed(1) : 'N/A' }}</td>
                    <td>{{ course.avg_attendance ? course.avg_attendance.toFixed(1) + '%' : 'N/A' }}</td>
                    <td>
                      <button class="btn btn-sm btn-outline-primary me-1" @click="viewCourseDetails(code)">
                        <i class="fas fa-chart-bar me-1"></i> Details
                      </button>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
            <div v-else class="placeholder-content">
              <p>No course data available.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </template>
  
  <script>
  import axios from 'axios'; // Make sure axios is imported
  
  export default {
    name: 'InstructorInsightsDashboard',
    data() {
      return {
        insights: {
          dashboard_data: {},
          narrative: ''
        },
        loading: true,
        error: null
      };
    },
    computed: {
      formattedNarrative() {
        // Keep the existing computed property for formatting the narrative
        if (!this.insights.narrative) return [];
        return this.insights.narrative.split('\n\n').filter(p => p.trim());
      }
    },
    mounted() {
      // Call fetchInsights when the component is mounted
      this.fetchInsights();
    },
    methods: {
      async fetchInsights() {
        this.loading = true;
        this.error = null;
  
        // --- Get token from localStorage ---
        const token = localStorage.getItem('authToken');
        // ---------------------------------
  
        // --- Check if token exists ---
        if (!token) {
          this.error = "Authentication token not found. Please log in again.";
          this.loading = false;
          // Optionally redirect to login page
          this.$router.push('/signin'); // Assuming '/signin' is your login route
          return; // Stop execution if no token
        }
        // ---------------------------------
  
        try {
          // --- Make the API call with the token ---
          const response = await axios.get('http://127.0.0.1:3000/api/instructor/insights', { // Make sure the URL is correct
            headers: {
              'Authorization': `Bearer ${token}` // Use the token retrieved from localStorage
            }
          });
          // -----------------------------------------
  
          // Assign the response data to the component's state
          this.insights = response.data;
  
        } catch (error) {
          console.error('Error fetching instructor insights:', error);
  
          // --- Handle specific errors, especially 401 ---
          if (error.response && error.response.status === 401) {
            // Unauthorized - token might be invalid or expired
            this.error = 'Your session may have expired or is invalid. Please log in again.';
            // Clear stored authentication data
            localStorage.removeItem('authToken');
            localStorage.removeItem('userRole');
            localStorage.removeItem('userEmail'); // Clear email if you stored it
            // Redirect to login page
            this.$router.push('/signin');
          } else {
            // Handle other errors (network error, server error, etc.)
            this.error = error.response?.data?.message || 'Failed to load insights. Please try again.';
          }
          // ---------------------------------------------
  
        } finally {
          // Ensure loading state is turned off regardless of success or failure
          this.loading = false;
        }
      },
  
      // Method to refresh the data by calling fetchInsights again
      refreshData() {
        this.fetchInsights();
      },
  
      // Method to navigate to detailed course insights view
      viewCourseDetails(courseCode) {
        // Assuming course code contains the ID or needs mapping
        // This mapping might need adjustment based on your actual data/routing
        const courseIdMatch = courseCode.match(/\d+/); // Simple extraction of numbers
        const courseId = courseIdMatch ? courseIdMatch[0] : null;
  
        if (courseId) {
          // Navigate to the specific course insight route
          this.$router.push(`/instructor/courses/${courseId}/insights`);
        } else {
          console.warn(`Could not extract ID from course code: ${courseCode}`);
          // Optionally show a user message that navigation failed
        }
      },
  
      // Helper method to determine CSS class based on risk score
      riskScoreClass(score) {
        if (score === null || score === undefined) return 'bg-secondary'; // Handle missing score
        if (score > 0.7) return 'bg-danger';
        if (score > 0.4) return 'bg-warning';
        return 'bg-success';
      },
  
      // Helper method to determine CSS class based on pass rate
      passRateClass(rate) {
        if (rate === null || rate === undefined) return ''; // Handle missing rate
        if (rate < 75) return 'text-danger';
        if (rate < 90) return 'text-warning';
        return 'text-success';
      }
    }
  };
  </script>
  
  <style scoped>
  .instructor-insights-dashboard {
    padding: 20px;
  }
  
  .page-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 20px;
  }
  
  .loading-container {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    padding: 50px 0;
  }
  
  .narrative-card {
    border-left: 4px solid #4285f4;
  }
  
  .narrative-paragraph {
    margin-bottom: 15px;
    line-height: 1.6;
  }
  
  .stat-card {
    height: 100%;
    text-align: center;
    transition: transform 0.2s;
  }
  
  .stat-card:hover {
    transform: translateY(-5px);
    box-shadow: 0 4px 8px rgba(0,0,0,0.1);
  }
  
  .stat-value {
    font-size: 2rem;
    font-weight: bold;
    margin: 0;
    color: #4285f4;
  }
  
  .risk-score {
    display: flex;
    align-items: center;
    gap: 10px;
  }
  
  .risk-score .progress {
    flex-grow: 1;
  }
  
  .placeholder-content {
    padding: 20px;
    text-align: center;
    color: #6c757d;
  }
  </style>