<template>
  <div :class="isDarkMode ? 'dark-mode' : 'light-mode'" class="dashboard-container">
    <div class="dashboard-content">
      <!-- Dashboard Header -->
      <header class="dashboard-header">
        <h1 class="dashboard-title">
          <span class="title-regular">Instructor</span>
          <span class="title-fancy">Insights Dashboard</span>
        </h1>
        <div class="header-actions">
          <button class="action-btn" @click="refreshData">
            <i class="fas fa-sync-alt me-2"></i> Refresh
          </button>
        </div>
      </header>

      <!-- Loading State -->
      <div v-if="loading" class="loading-container">
        <div class="loading-indicator" role="status">
          <span class="visually-hidden">Loading...</span>
        </div>
        <p>Analyzing your teaching data...</p>
      </div>

      <!-- Error State -->
      <div v-if="error" class="alert-container">
        <div class="alert-message">
          <strong>Error:</strong> {{ error }}
        </div>
      </div>

      <!-- Dashboard Content -->
      <div v-if="!loading && !error" class="dashboard-main">
        <!-- Key Metrics Overview -->
        <div class="stats-grid">
          <div class="stat-card">
            <h3>Total Courses</h3>
            <p class="stat-value">{{ insights.dashboard_data?.total_courses || 0 }}</p>
            <p class="stat-trend">Current Semester</p>
          </div>
          <div class="stat-card">
            <h3>Total Students</h3>
            <p class="stat-value">{{ insights.dashboard_data?.total_students || 0 }}</p>
            <p class="stat-trend">Across all courses</p>
          </div>
          <div class="stat-card">
            <h3>At-Risk Students</h3>
            <p class="stat-value">{{ insights.dashboard_data?.at_risk_students_count || 0 }}</p>
            <p class="stat-trend">Need attention</p>
          </div>
          <div class="stat-card">
            <h3>Avg. Instructor Rating</h3>
            <p class="stat-value">
              {{ insights.dashboard_data?.overall_metrics?.avg_instructor_rating?.toFixed(1) || 'N/A' }}
              <small>/5</small>
            </p>
            <p class="stat-trend positive">↑ 0.2 from last semester</p>
          </div>
        </div>

        <!-- AI-Generated Narrative Card with Markdown Support -->
        <div class="dashboard-card narrative-card">
          <div class="card-header">
            <h2>
              <i class="fas fa-robot me-2"></i> AI-Generated Insights
            </h2>
            <span class="badge">Generated by Gemini</span>
          </div>
          <div class="card-body">
            <div v-if="insights.narrative" class="narrative-content">
              <div 
                v-for="(paragraph, index) in formattedNarrative" 
                :key="index" 
                class="narrative-paragraph"
                v-html="renderMarkdown(paragraph)"
              ></div>
            </div>
            <div v-else class="placeholder-content">
              <p>No narrative available. Try refreshing the data.</p>
            </div>
          </div>
        </div>

        <!-- At-Risk Students Section -->
        <div class="dashboard-card">
          <div class="card-header">
            <h2>
              <i class="fas fa-exclamation-triangle me-2"></i> At-Risk Students
            </h2>
          </div>
          <div class="card-body">
            <div v-if="insights.dashboard_data?.at_risk_students?.length" class="table-section">
              <div class="table-container">
                <table class="dashboard-table">
                  <thead>
                    <tr>
                      <th>Student</th>
                      <th>Risk Score</th>
                      <th>Current Trimester</th>
                      <th>Key Factors</th>
                      <th>Actions</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr v-for="student in paginatedAtRiskStudents" :key="student.student_id">
                      <td>{{ student.name }}</td>
                      <td>
                        <div class="risk-score">
                          <div class="progress">
                            <div
                              class="progress-bar"
                              :class="riskScoreClass(student.risk_score)"
                              role="progressbar"
                              :style="{ width: `${student.risk_score * 100}%` }"
                              :aria-valuenow="student.risk_score * 100"
                              aria-valuemin="0"
                              aria-valuemax="100"
                            ></div>
                          </div>
                          <span>{{ (student.risk_score * 100).toFixed(0) }}%</span>
                        </div>
                      </td>
                      <td>{{ student.current_trimester }}</td>
                      <td>
                        <span
                          v-for="(factor, index) in student.key_factors"
                          :key="index"
                          class="factor-badge"
                        >
                          {{ factor }}
                        </span>
                      </td>
                      <td>
                        <button class="action-btn-small">
                          <i class="fas fa-envelope me-1"></i> Contact
                        </button>
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>
              
              <div class="pagination-controls">
                <button 
                  class="pagination-btn" 
                  :disabled="atRiskCurrentPage === 1"
                  @click="atRiskCurrentPage--"
                >
                  <i class="fas fa-chevron-left"></i>
                </button>
                <span>Page {{ atRiskCurrentPage }} of {{ totalAtRiskPages }}</span>
                <button 
                  class="pagination-btn" 
                  :disabled="atRiskCurrentPage === totalAtRiskPages"
                  @click="atRiskCurrentPage++"
                >
                  <i class="fas fa-chevron-right"></i>
                </button>
              </div>
              
              <!-- Risk Distribution Chart -->
              <div class="chart-container">
                <h3 class="chart-title">Risk Factor Distribution</h3>
                <div class="chart-wrapper" ref="riskFactorChart"></div>
              </div>
            </div>
            <div v-else class="placeholder-content">
              <p>No at-risk students identified at this time.</p>
            </div>
          </div>
        </div>

        <!-- Course Performance Overview -->
        <div class="dashboard-card">
          <div class="card-header">
            <h2>
              <i class="fas fa-book me-2"></i> Course Performance
            </h2>
          </div>
          <div class="card-body">
            <div v-if="Object.keys(insights.dashboard_data?.courses || {}).length" class="table-section">
              <div class="table-container">
                <table class="dashboard-table">
                  <thead>
                    <tr>
                      <th>Course</th>
                      <th>Pass Rate</th>
                      <th>Avg. Quiz 1</th>
                      <th>Avg. Quiz 2</th>
                      <th>Avg. Endterm</th>
                      <th>Attendance</th>
                      <th>Actions</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr v-for="course in paginatedCourses" :key="course.code">
                      <td>{{ course.course_name }}</td>
                      <td>
                        <span :class="passRateClass(course.pass_rate)">
                          {{ course.pass_rate ? course.pass_rate.toFixed(1) + '%' : 'N/A' }}
                        </span>
                      </td>
                      <td>{{ course.avg_quiz1 ? course.avg_quiz1.toFixed(1) : 'N/A' }}</td>
                      <td>{{ course.avg_quiz2 ? course.avg_quiz2.toFixed(1) : 'N/A' }}</td>
                      <td>{{ course.avg_endterm ? course.avg_endterm.toFixed(1) : 'N/A' }}</td>
                      <td>{{ course.avg_attendance ? course.avg_attendance.toFixed(1) + '%' : 'N/A' }}</td>
                      <td>
                        <button class="action-btn-small" @click="viewCourseDetails(course.code)">
                          <i class="fas fa-chart-bar me-1"></i> Details
                        </button>
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>
              
              <div class="pagination-controls">
                <button 
                  class="pagination-btn" 
                  :disabled="coursesCurrentPage === 1"
                  @click="coursesCurrentPage--"
                >
                  <i class="fas fa-chevron-left"></i>
                </button>
                <span>Page {{ coursesCurrentPage }} of {{ totalCoursesPages }}</span>
                <button 
                  class="pagination-btn" 
                  :disabled="coursesCurrentPage === totalCoursesPages"
                  @click="coursesCurrentPage++"
                >
                  <i class="fas fa-chevron-right"></i>
                </button>
              </div>
              
              <!-- Course Performance Chart -->
              <div class="chart-container">
                <h3 class="chart-title">Course Performance Metrics</h3>
                <div class="chart-wrapper" ref="coursePerformanceChart"></div>
              </div>
            </div>
            <div v-else class="placeholder-content">
              <p>No course data available.</p>
            </div>
          </div>
        </div>
      </div>
    </div>

    <footer class="dashboard-footer">
      Made with ❤️ by DevAstators, And Special thanks to Dobby
    </footer>
  </div>
</template>

<script>
import axios from 'axios';
import * as d3 from 'd3';
import { marked } from 'marked'; // Import marked for Markdown rendering
import DOMPurify from 'dompurify'; // Import DOMPurify for sanitizing HTML

export default {
  name: 'InstructorInsightsDashboard',
  data() {
    return {
      insights: {
        dashboard_data: {
          courses: {},
          at_risk_students: []
        },
        narrative: ''
      },
      loading: true,
      error: null,
      isDarkMode: true,
      itemsPerPage: 10,
      atRiskCurrentPage: 1,
      coursesCurrentPage: 1
    };
  },
  computed: {
    formattedNarrative() {
      if (!this.insights.narrative) return [];
      // Split by double newlines to identify paragraphs
      return this.insights.narrative.split('\n\n').filter(p => p.trim());
    },
    
    // Pagination for at-risk students
    paginatedAtRiskStudents() {
      if (!this.insights.dashboard_data?.at_risk_students) return [];
      
      const start = (this.atRiskCurrentPage - 1) * this.itemsPerPage;
      const end = start + this.itemsPerPage;
      
      return this.insights.dashboard_data.at_risk_students.slice(start, end);
    },
    
    totalAtRiskPages() {
      if (!this.insights.dashboard_data?.at_risk_students) return 1;
      return Math.ceil(this.insights.dashboard_data.at_risk_students.length / this.itemsPerPage);
    },
    
    // Pagination for courses
    paginatedCourses() {
      if (!this.insights.dashboard_data?.courses) return [];
      
      const coursesArray = Object.entries(this.insights.dashboard_data.courses).map(([code, data]) => {
        return { code, ...data };
      });
      
      const start = (this.coursesCurrentPage - 1) * this.itemsPerPage;
      const end = start + this.itemsPerPage;
      
      return coursesArray.slice(start, end);
    },
    
    totalCoursesPages() {
      if (!this.insights.dashboard_data?.courses) return 1;
      return Math.ceil(Object.keys(this.insights.dashboard_data.courses).length / this.itemsPerPage);
    }
  },
  created() {
    this.checkAuthentication();
  },
  mounted() {
    this.fetchInsights();
  },
  updated() {
    this.renderCharts();
  },
  methods: {
    // Method for rendering markdown
    renderMarkdown(text) {
      // Configure marked options if needed
      marked.setOptions({
        breaks: true, // Add line breaks on single line breaks
        gfm: true,    // Enable GitHub Flavored Markdown
      });
      
      // Parse markdown and sanitize the resulting HTML
      const rawHtml = marked.parse(text);
      return DOMPurify.sanitize(rawHtml);
    },

    getAuthToken() {
      // Retrieve the JWT token from localStorage
      return localStorage.getItem('authToken');
    },
    
    checkAuthentication() {
      const token = this.getAuthToken();
      if (!token) {
        this.$router.push('/signin');
      }
    },
    
    async fetchInsights() {
      this.loading = true;
      this.error = null;

      const token = localStorage.getItem('authToken');

      if (!token) {
        this.error = "Authentication token not found. Please log in again.";
        this.loading = false;
        this.$router.push('/signin');
        return;
      }

      try {
        const response = await axios.get('http://127.0.0.1:3000/api/instructor/insights', {
          headers: {
            'Authorization': token
          }
        });
        
        this.insights = response.data;
        
        // Reset pagination when data changes
        this.atRiskCurrentPage = 1;
        this.coursesCurrentPage = 1;
        
        // Render charts after data is loaded
        this.$nextTick(() => {
          this.renderCharts();
        });

      } catch (error) {
        console.error('Error fetching instructor insights:', error);

        if (error.response && error.response.status === 401) {
          this.error = 'Your session may have expired or is invalid. Please log in again.';
          localStorage.removeItem('authToken');
          localStorage.removeItem('userRole');
          localStorage.removeItem('userEmail');
          this.$router.push('/signin');
        } else {
          this.error = error.response?.data?.message || 'Failed to load insights. Please try again.';
        }

      } finally {
        this.loading = false;
      }
    },

    refreshData() {
      this.fetchInsights();
    },

    viewCourseDetails(courseCode) {
      const courseIdMatch = courseCode.match(/\d+/);
      const courseId = courseIdMatch ? courseIdMatch[0] : null;

      if (courseId) {
        this.$router.push(`/instructor/courses/${courseId}/insights`);
      } else {
        console.warn(`Could not extract ID from course code: ${courseCode}`);
      }
    },

    riskScoreClass(score) {
      if (score === null || score === undefined) return 'bg-secondary';
      if (score > 0.7) return 'bg-danger';
      if (score > 0.4) return 'bg-warning';
      return 'bg-success';
    },

    passRateClass(rate) {
      if (rate === null || rate === undefined) return '';
      if (rate < 75) return 'text-danger';
      if (rate < 90) return 'text-warning';
      return 'text-success';
    },
    
    renderCharts() {
      if (this.loading || this.error) return;
      
      // Only render if we have data and the DOM elements exist
      if (this.$refs.riskFactorChart && this.insights.dashboard_data?.at_risk_students?.length > 0) {
        this.renderRiskFactorChart();
      }
      
      if (this.$refs.coursePerformanceChart && Object.keys(this.insights.dashboard_data?.courses || {}).length > 0) {
        this.renderCoursePerformanceChart();
      }
    },
    
    renderRiskFactorChart() {
      // Clear previous chart
      d3.select(this.$refs.riskFactorChart).selectAll("*").remove();
      
      const factors = {};
      
      // Count occurrence of each risk factor
      this.insights.dashboard_data.at_risk_students.forEach(student => {
        student.key_factors.forEach(factor => {
          factors[factor] = (factors[factor] || 0) + 1;
        });
      });
      
      // Convert to array for D3
      const data = Object.entries(factors).map(([name, count]) => ({ name, count }));
      data.sort((a, b) => b.count - a.count);
      
      // Set up dimensions with more padding for labels
      const margin = { top: 30, right: 30, bottom: 90, left: 40 };
      const width = this.$refs.riskFactorChart.clientWidth - margin.left - margin.right;
      const height = 300 - margin.top - margin.bottom;
      
      // Create SVG
      const svg = d3.select(this.$refs.riskFactorChart)
        .append("svg")
        .attr("width", width + margin.left + margin.right)
        .attr("height", height + margin.top + margin.bottom)
        .append("g")
        .attr("transform", `translate(${margin.left},${margin.top})`);
      
      // X scale
      const x = d3.scaleBand()
        .domain(data.map(d => d.name))
        .range([0, width])
        .padding(0.4);
      
      // Y scale with more padding at the top
      const y = d3.scaleLinear()
        .domain([0, d3.max(data, d => d.count) * 1.1])
        .range([height, 0]);
      
      // Use improved color palette that matches dashboard theme
      const colorPalette = ['#8b5cf6', '#a78bfa', '#c4b5fd', '#7c3aed', '#6d28d9', '#5b21b6'];
      const color = d3.scaleOrdinal()
        .domain(data.map(d => d.name))
        .range(colorPalette);
      
      // Add X axis with rotated labels for better fit
      svg.append("g")
        .attr("transform", `translate(0,${height})`)
        .call(d3.axisBottom(x))
        .selectAll("text")
        .attr("transform", "translate(-10,5)rotate(-45)")
        .style("text-anchor", "end")
        .style("font-size", "11px");
      
      // Add Y axis with better spacing
      svg.append("g")
        .call(d3.axisLeft(y).ticks(5).tickFormat(d => d))
        .selectAll("text")
        .style("font-size", "11px");
      
      // Add grid lines for better readability
      svg.append("g")
        .attr("class", "grid")
        .attr("opacity", 0.1)
        .call(d3.axisLeft(y)
          .ticks(5)
          .tickSize(-width)
          .tickFormat("")
        );
      
      // Create gradient for bars
      const defs = svg.append("defs");
      data.forEach((d, i) => {
        const gradientId = `bar-gradient-${i}`;
        const gradient = defs.append("linearGradient")
          .attr("id", gradientId)
          .attr("x1", "0%")
          .attr("y1", "0%")
          .attr("x2", "0%")
          .attr("y2", "100%");
          
        gradient.append("stop")
          .attr("offset", "0%")
          .attr("stop-color", d3.rgb(color(d.name)).brighter(0.5));
          
        gradient.append("stop")
          .attr("offset", "100%")
          .attr("stop-color", color(d.name));
      });
      
      // Create bars with rounded corners and gradients
      svg.selectAll(".bar")
        .data(data)
        .enter()
        .append("rect")
        .attr("class", "bar")
        .attr("x", d => x(d.name))
        .attr("width", x.bandwidth())
        .attr("y", d => y(d.count))
        .attr("height", d => height - y(d.count))
        .attr("rx", 4)
        .attr("ry", 4)
        .attr("fill", (d, i) => `url(#bar-gradient-${i})`)
        .style("filter", "drop-shadow(0px 2px 3px rgba(0, 0, 0, 0.2))");
      
      // Add value labels on top of bars
      svg.selectAll(".bar-label")
        .data(data)
        .enter()
        .append("text")
        .attr("class", "bar-label")
        .attr("x", d => x(d.name) + x.bandwidth() / 2)
        .attr("y", d => y(d.count) - 5)
        .attr("text-anchor", "middle")
        .style("font-size", "10px")
        .style("font-weight", "bold")
        .text(d => d.count);
    },
    
    renderCoursePerformanceChart() {
      // Clear previous chart
      d3.select(this.$refs.coursePerformanceChart).selectAll("*").remove();
      
      // Convert course data to array
      const courseData = Object.entries(this.insights.dashboard_data.courses).map(([code, data]) => {
        return { 
          code, 
          name: data.course_name,
          metrics: [
            { name: "Pass Rate", value: data.pass_rate || 0 },
            { name: "Attendance", value: data.avg_attendance || 0 }
          ]
        };
      });
      
      // Limit to top 6 courses for clarity
      const topCourses = courseData.slice(0, 6);
      
      // Set up dimensions with more padding for labels
      const margin = { top: 40, right: 150, bottom: 60, left: 70 };
      const width = this.$refs.coursePerformanceChart.clientWidth - margin.left - margin.right;
      const height = 300 - margin.top - margin.bottom;
      
      // Create SVG
      const svg = d3.select(this.$refs.coursePerformanceChart)
        .append("svg")
        .attr("width", width + margin.left + margin.right)
        .attr("height", height + margin.top + margin.bottom)
        .append("g")
        .attr("transform", `translate(${margin.left},${margin.top})`);
      
      // Define metrics to display with nicer colors
      const metrics = ["Pass Rate", "Attendance"];
      
      // Use color palette that matches dashboard theme
      const colorPalette = {
        "Pass Rate": "#8b5cf6",   // Purple - matches primary gradient color
        "Attendance": "#ec4899"   // Pink - matches secondary gradient color
      };
      
      // Set up scales
      const x = d3.scaleBand()
        .domain(topCourses.map(d => d.name))
        .range([0, width])
        .padding(0.1);
      
      const y = d3.scaleLinear()
        .domain([0, 100])
        .range([height, 0]);
      
      // Add grid lines for better readability
      svg.append("g")
        .attr("class", "grid")
        .attr("opacity", 0.1)
        .call(d3.axisLeft(y)
          .ticks(5)
          .tickSize(-width)
          .tickFormat("")
        );
      
      // Add smooth curve between points
      const line = d3.line()
        .x(d => x(d.course) + x.bandwidth() / 2)
        .y(d => y(d.value))
        .curve(d3.curveMonotoneX);  // Smoother curve
      
      // Create lines for each metric
      metrics.forEach(metric => {
        const metricData = topCourses.map(course => {
          const metricObj = course.metrics.find(m => m.name === metric);
          return {
            course: course.name,
            value: metricObj ? metricObj.value : 0
          };
        });
        
        // Add gradient for line
        const gradientId = `line-gradient-${metric.replace(/\s+/g, '-')}`;
        const gradient = svg.append("linearGradient")
          .attr("id", gradientId)
          .attr("gradientUnits", "userSpaceOnUse")
          .attr("x1", 0)
          .attr("y1", height)
          .attr("x2", 0)
          .attr("y2", 0);
          
        gradient.append("stop")
          .attr("offset", "0%")
          .attr("stop-color", colorPalette[metric])
          .attr("stop-opacity", 0.5);
          
        gradient.append("stop")
          .attr("offset", "100%")
          .attr("stop-color", colorPalette[metric]);
        
        // Draw line with improved styling
        svg.append("path")
          .datum(metricData)
          .attr("fill", "none")
          .attr("stroke", colorPalette[metric])
          .attr("stroke-width", 3)
          .attr("stroke-linecap", "round")
          .attr("stroke-linejoin", "round")
          .style("filter", "drop-shadow(0px 2px 3px rgba(0, 0, 0, 0.2))")
          .attr("d", line);
        
        // Add dots with improved styling
        svg.selectAll(`.dot-${metric.replace(/\s+/g, '-')}`)
          .data(metricData)
          .enter()
          .append("circle")
          .attr("class", `dot-${metric.replace(/\s+/g, '-')}`)
          .attr("cx", d => x(d.course) + x.bandwidth() / 2)
          .attr("cy", d => y(d.value))
          .attr("r", 6)
          .attr("fill", "#fff")  // White center
          .attr("stroke", colorPalette[metric])
          .attr("stroke-width", 3)
          .style("filter", "drop-shadow(0px 2px 3px rgba(0, 0, 0, 0.1))");
        
        // Add value labels above points
        svg.selectAll(`.value-${metric.replace(/\s+/g, '-')}`)
          .data(metricData)
          .enter()
          .append("text")
          .attr("class", `value-${metric.replace(/\s+/g, '-')}`)
          .attr("x", d => x(d.course) + x.bandwidth() / 2)
          .attr("y", d => y(d.value) - 10)
          .attr("text-anchor", "middle")
          .style("font-size", "10px")
          .style("font-weight", "bold")
          .text(d => `${d.value.toFixed(0)}%`);
      });
      
      // Add X axis with angled labels for better fit
      svg.append("g")
        .attr("transform", `translate(0,${height})`)
        .call(d3.axisBottom(x))
        .selectAll("text")
        .attr("transform", "translate(-10,5)rotate(-40)")
        .style("text-anchor", "end")
        .style("font-size", "11px");
      
      // Add Y axis with better formatting
      svg.append("g")
        .call(d3.axisLeft(y).ticks(5).tickFormat(d => d + "%"))
        .selectAll("text")
        .style("font-size", "11px");
      
      // Add more elegant legend
      const legend = svg.append("g")
        .attr("transform", `translate(${width + 20}, 10)`);
      
      metrics.forEach((metric, i) => {
        const legendRow = legend.append("g")
          .attr("transform", `translate(0, ${i * 25})`);
        
        // Legend color box with rounded corners
        legendRow.append("rect")
          .attr("width", 12)
          .attr("height", 12)
          .attr("rx", 3)
          .attr("ry", 3)
          .attr("fill", colorPalette[metric]);
        
        // Legend text
        legendRow.append("text")
          .attr("x", 20)
          .attr("y", 9)
          .text(metric)
          .style("font-size", "12px");
      });
    }
  }
};
</script>
<style scoped>
/* Theme Variables */
.dark-mode {
  --background: #121212;
  --card-bg: rgba(255, 255, 255, 0.05);
  --card-border: rgba(255, 255, 255, 0.1);
  --text: #e1e1e1;
  --text-secondary: #a0a0a0;
  --primary: rgb(99, 102, 241);
  --primary-gradient: linear-gradient(to right, rgb(99, 102, 241), rgb(168, 85, 247));
  --danger: #ef4444;
  --warning: #f59e0b;
  --success: #10b981;
  --item-bg: rgba(255, 255, 255, 0.03);
  background-color: var(--background);
  color: var(--text);
}

.light-mode {
  --background: #f5f5f7;
  --card-bg: rgba(255, 255, 255, 0.9);
  --card-border: rgba(0, 0, 0, 0.1);
  --text: #333333;
  --text-secondary: #666666;
  --primary: rgb(99, 102, 241);
  --primary-gradient: linear-gradient(to right, rgb(99, 102, 241), rgb(168, 85, 247));
  --danger: #ef4444;
  --warning: #f59e0b;
  --success: #10b981;
  --item-bg: rgba(0, 0, 0, 0.03);
  background-color: var(--background);
  color: var(--text);
}

.dashboard-container {
  min-height: 100vh;
  padding: 2rem;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
}

.dashboard-content {
  position: relative;
  z-index: 10;
  max-width: 1280px;
  margin: 0 auto;
}

/* Dashboard Header */
.dashboard-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 2rem;
}

.dashboard-title {
  font-size: clamp(1.5rem, 4vw, 2.5rem);
  margin-bottom: 0.5rem;
}

.title-regular {
  color: var(--text);
}

.title-fancy {
  font-family: 'Pacifico', cursive;
  background: var(--primary-gradient);
  -webkit-background-clip: text;
  color: transparent;
  margin-left: 0.5rem;
}

/* Action Button Styling */
.action-btn {
  padding: 0.5rem 1rem;
  background: var(--primary-gradient);
  border: none;
  border-radius: 0.5rem;
  color: white;
  cursor: pointer;
  font-weight: bold;
  font-size: 0.9rem;
  transition: all 0.2s;
  display: flex;
  align-items: center;
  gap: 0.5rem;
}

.action-btn:hover {
  opacity: 0.9;
  transform: translateY(-1px);
  box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
}

.action-btn-small {
  padding: 0.375rem 0.75rem;
  background: rgba(99, 102, 241, 0.2);
  border: none;
  border-radius: 0.5rem;
  color: var(--primary);
  cursor: pointer;
  font-size: 0.875rem;
  transition: background 0.3s;
}

.action-btn-small:hover {
  background: rgba(99, 102, 241, 0.3);
}

/* Loading Container */
.loading-container {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  padding: 50px 0;
}

.loading-indicator {
  width: 3rem;
  height: 3rem;
  border: 4px solid rgba(0, 0, 0, 0.1);
  border-radius: 50%;
  border-top-color: var(--primary);
  animation: spin 1s infinite linear;
  margin-bottom: 1rem;
}

@keyframes spin {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}

/* Alert Container */
.alert-container {
  margin-bottom: 2rem;
}

.alert-message {
  padding: 1rem;
  background-color: rgba(239, 68, 68, 0.2);
  border-radius: 0.5rem;
  color: var(--danger);
}

/* Stats Grid - update to match InstructorDashboard */
.stats-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(240px, 1fr));
  gap: 1rem;
  margin-bottom: 2rem;
}

.stat-card {
  background: var(--card-bg);
  backdrop-filter: blur(10px);
  padding: 1.5rem;
  border-radius: 1rem;
  border: 1px solid var(--card-border);
  transition: transform 0.2s;
}

.stat-card:hover {
  transform: translateY(-5px);
  box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
}

.stat-value {
  font-size: 2rem;
  font-weight: bold;
  margin: 0.5rem 0;
  background: var(--primary-gradient);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
}

.stat-trend {
  font-size: 0.9rem;
  color: var(--text-secondary);
}

.stat-trend.positive {
  color: var(--success);
}

/* Narrative Card - using AI analytics style */
.narrative-card {
  margin-bottom: 1.5rem;
  background: linear-gradient(135deg, rgba(56, 189, 248, 0.1), rgba(14, 165, 233, 0.1));
  backdrop-filter: blur(10px);
  padding: 1.5rem;
  border-radius: 1rem;
  border: 1px solid var(--card-border);
  border-left: 4px solid var(--primary);
}

.narrative-content {
  line-height: 1.6;
}

.narrative-paragraph {
  margin-bottom: 15px;
}

/* Markdown rendering styles */
.narrative-paragraph :deep(h1),
.narrative-paragraph :deep(h2),
.narrative-paragraph :deep(h3),
.narrative-paragraph :deep(h4) {
  margin-top: 1.5rem;
  margin-bottom: 0.75rem;
  font-weight: 600;
}

.narrative-paragraph :deep(strong) {
  font-weight: 600;
}

.narrative-paragraph :deep(a) {
  color: var(--primary);
  text-decoration: none;
}

.narrative-paragraph :deep(a:hover) {
  text-decoration: underline;
}

.narrative-paragraph :deep(code) {
  font-family: monospace;
  background: rgba(255, 255, 255, 0.1);
  padding: 0.1rem 0.3rem;
  border-radius: 0.25rem;
}

.narrative-paragraph :deep(blockquote) {
  border-left: 4px solid var(--primary);
  padding-left: 1rem;
  margin-left: 0;
  color: var(--text-secondary);
  font-style: italic;
}

/* Dashboard Cards */
.dashboard-card {
  background: var(--card-bg);
  backdrop-filter: blur(10px);
  padding: 1.5rem;
  border-radius: 1rem;
  border: 1px solid var(--card-border);
  margin-bottom: 1.5rem;
}

.card-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 1.5rem;
}

.card-header h2 {
  font-size: 1.5rem;
  margin: 0;
  display: flex;
  align-items: center;
}

.badge {
  padding: 0.25rem 0.75rem;
  background: var(--primary-gradient);
  color: white;
  border-radius: 1rem;
  font-size: 0.8rem;
}

/* Custom card gradients to match InstructorDashboard */
.card-body {
  position: relative;
}

.table-section {
  display: flex;
  flex-direction: column;
  gap: 1.5rem;
}

.table-container {
  max-height: 350px;
  overflow-y: auto;
  border-radius: 0.5rem;
  border: 1px solid var(--card-border);
}

/* Tables */
.dashboard-table {
  width: 100%;
  border-collapse: collapse;
}

.dashboard-table th,
.dashboard-table td {
  padding: 1rem;
  text-align: left;
  border-bottom: 1px solid var(--card-border);
}

.dashboard-table th {
  position: sticky;
  top: 0;
  background: rgba(0, 0, 0, 0.2);
  font-weight: bold;
  color: var(--text-secondary);
  z-index: 10;
}

.dashboard-table tr:hover {
  background: var(--item-bg);
}

/* Risk Score */
.risk-score {
  display: flex;
  align-items: center;
  gap: 0.5rem;
}

.progress {
  flex: 1;
  height: 8px;
  background-color: rgba(255, 255, 255, 0.1);
  border-radius: 4px;
  overflow: hidden;
}

.progress-bar {
  height: 100%;
  border-radius: 4px;
}

.bg-danger {
  background-color: var(--danger);
}

.bg-warning {
  background-color: var(--warning);
}

.bg-success {
  background-color: var(--success);
}

.bg-secondary {
  background-color: var(--text-secondary);
}

/* Factor badges */
.factor-badge {
  display: inline-block;
  padding: 0.25rem 0.5rem;
  margin: 0.25rem;
  font-size: 0.8rem;
  background-color: var(--item-bg);
  border-radius: 0.5rem;
  color: var(--text-secondary);
  border: 1px solid rgba(99, 102, 241, 0.2);
  transition: all 0.2s ease;
}

.factor-badge:hover {
  background-color: rgba(99, 102, 241, 0.1);
  transform: translateY(-1px);
}

/* Text Colors */
.text-danger {
  color: var(--danger);
}

.text-warning {
  color: var(--warning);
}

.text-success {
  color: var(--success);
}

/* Pagination Controls */
.pagination-controls {
  display: flex;
  justify-content: center;
  align-items: center;
  gap: 1rem;
  margin: 0.5rem 0;
}

.pagination-btn {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 2rem;
  height: 2rem;
  border-radius: 50%;
  border: none;
  background-color: var(--item-bg);
  color: var(--text);
  cursor: pointer;
  transition: all 0.2s;
}

.pagination-btn:hover {
  background: var(--primary-gradient);
  color: white;
  transform: translateY(-1px);
}

.pagination-btn:disabled {
  opacity: 0.5;
  cursor: not-allowed;
  transform: none;
}

/* Charts */
.chart-container {
  margin-top: 1.5rem;
}

.chart-title {
  font-size: 1.1rem;
  margin-bottom: 1rem;
  color: var(--text);
}

.chart-wrapper {
  width: 100%;
  height: 300px;
  background: var(--item-bg);
  border-radius: 0.5rem;
  padding: 1rem;
  overflow: hidden;
  transition: all 0.3s ease;
}

.chart-wrapper:hover {
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
}

/* Placeholder content */
.placeholder-content {
  padding: 1.5rem;
  text-align: center;
  color: var(--text-secondary);
}

/* Footer */
.dashboard-footer {
  text-align: center;
  padding: 1rem;
  font-size: 0.8rem;
  color: var(--text-secondary);
  border-top: 1px solid var(--card-border);
  margin-top: 2rem;
}

/* Light Mode Adjustments for charts */
.light-mode .chart-wrapper {
  background: rgba(255, 255, 255, 0.8);
  border: 1px solid var(--card-border);
}

.light-mode .dashboard-table th {
  background: rgba(240, 240, 240, 0.9);
  color: var(--text-secondary);
}

.light-mode .progress {
  background-color: rgba(0, 0, 0, 0.1);
}

.light-mode .factor-badge {
  background-color: rgba(0, 0, 0, 0.05);
}

/* Make table more visually appealing */
.light-mode .dashboard-table tr:hover {
  background-color: rgba(99, 102, 241, 0.05);
}

.dark-mode .dashboard-table tr:hover {
  background-color: rgba(99, 102, 241, 0.1);
}

/* Gradient backgrounds for cards to match InstructorDashboard */
.dashboard-main > .dashboard-card:nth-child(3) {
  background: linear-gradient(135deg, rgba(99, 102, 241, 0.05), rgba(168, 85, 247, 0.05));
}

.dashboard-main > .dashboard-card:nth-child(4) {
  background: linear-gradient(135deg, rgba(236, 72, 153, 0.05), rgba(239, 68, 68, 0.05));
}

.dashboard-main > .dashboard-card:nth-child(5) {
  background: linear-gradient(135deg, rgba(16, 185, 129, 0.05), rgba(5, 150, 105, 0.05));
}

/* Scrollbar Styling */
.table-container::-webkit-scrollbar {
  width: 8px;
  height: 8px;
}

.table-container::-webkit-scrollbar-track {
  background: var(--item-bg);
  border-radius: 4px;
}

.table-container::-webkit-scrollbar-thumb {
  background: var(--text-secondary);
  border-radius: 4px;
}

.table-container::-webkit-scrollbar-thumb:hover {
  background: var(--primary);
}

/* Empty state styling */
.empty-state {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  padding: 2rem;
  text-align: center;
  background: var(--item-bg);
  border-radius: 0.5rem;
  min-height: 150px;
}

.empty-icon {
  font-size: 2.5rem;
  margin-bottom: 1rem;
  opacity: 0.7;
}

.empty-state p {
  margin: 0 0 0.5rem 0;
  font-size: 1rem;
  color: var(--text-secondary);
}

.empty-subtext {
  font-size: 0.85rem;
  opacity: 0.7;
}

/* Utility classes for spacing */
.me-1 {
  margin-right: 0.25rem;
}

.me-2 {
  margin-right: 0.5rem;
}

/* Responsive Adjustments */
@media (max-width: 768px) {
  .dashboard-container {
    padding: 1rem;
  }

  .dashboard-header {
    flex-direction: column;
    align-items: flex-start;
    gap: 1rem;
  }

  .stats-grid {
    grid-template-columns: 1fr;
  }

  .card-header {
    flex-direction: column;
    align-items: flex-start;
    gap: 0.5rem;
  }

  .chart-wrapper {
    height: 250px;
  }
  
  .dashboard-table th,
  .dashboard-table td {
    padding: 0.75rem 0.5rem;
    font-size: 0.9rem;
  }
}
</style>