<template>
  <div :class="isDarkMode ? 'dark-mode' : 'light-mode'" class="dashboard-container">
    <div class="dashboard-content">
      <!-- Dashboard Header -->
      <header class="dashboard-header">
        <h1 class="dashboard-title">
          <span class="title-regular">Instructor</span>
          <span class="title-fancy">Insights Dashboard</span>
        </h1>
        <div class="header-actions">
          <button class="action-btn" @click="refreshData">
            <i class="fas fa-sync-alt me-2"></i> Refresh
          </button>
        </div>
      </header>

      <!-- Loading State -->
      <div v-if="loading" class="loading-container">
        <div class="spinner-border text-primary" role="status">
          <span class="visually-hidden">Loading...</span>
        </div>
        <p>Analyzing your teaching data...</p>
      </div>

      <!-- Error State -->
      <div v-if="error" class="alert-container">
        <div class="alert-message">
          <strong>Error:</strong> {{ error }}
        </div>
      </div>

      <!-- Dashboard Content -->
      <div v-if="!loading && !error" class="dashboard-main">
        <!-- Key Metrics Overview -->
        <div class="stats-grid">
          <div class="stat-card">
            <h3>Total Courses</h3>
            <p class="stat-value">{{ insights.dashboard_data?.total_courses || 0 }}</p>
            <p class="stat-trend">Current Semester</p>
          </div>
          <div class="stat-card">
            <h3>Total Students</h3>
            <p class="stat-value">{{ insights.dashboard_data?.total_students || 0 }}</p>
            <p class="stat-trend">Across all courses</p>
          </div>
          <div class="stat-card">
            <h3>At-Risk Students</h3>
            <p class="stat-value">{{ insights.dashboard_data?.at_risk_students_count || 0 }}</p>
            <p class="stat-trend">Need attention</p>
          </div>
          <div class="stat-card">
            <h3>Avg. Instructor Rating</h3>
            <p class="stat-value">
              {{ insights.dashboard_data?.overall_metrics?.avg_instructor_rating?.toFixed(1) || 'N/A' }}
              <small>/5</small>
            </p>
            <p class="stat-trend positive">↑ 0.2 from last semester</p>
          </div>
        </div>

        <!-- AI-Generated Narrative Card -->
        <div class="dashboard-card narrative-card">
          <div class="card-header">
            <h2>
              <i class="fas fa-robot me-2"></i> AI-Generated Insights
            </h2>
            <span class="badge">Generated by Gemini</span>
          </div>
          <div class="card-body">
            <div v-if="insights.narrative" class="narrative-content">
              <p v-for="(paragraph, index) in formattedNarrative" :key="index" class="narrative-paragraph">
                {{ paragraph }}
              </p>
            </div>
            <div v-else class="placeholder-content">
              <p>No narrative available. Try refreshing the data.</p>
            </div>
          </div>
        </div>

        <!-- At-Risk Students Section -->
        <div class="dashboard-card">
          <div class="card-header">
            <h2>
              <i class="fas fa-exclamation-triangle me-2"></i> At-Risk Students
            </h2>
          </div>
          <div class="card-body">
            <div v-if="insights.dashboard_data?.at_risk_students?.length" class="table-responsive">
              <table class="dashboard-table">
                <thead>
                  <tr>
                    <th>Student</th>
                    <th>Risk Score</th>
                    <th>Current Trimester</th>
                    <th>Key Factors</th>
                    <th>Actions</th>
                  </tr>
                </thead>
                <tbody>
                  <tr v-for="student in insights.dashboard_data.at_risk_students" :key="student.student_id">
                    <td>{{ student.name }}</td>
                    <td>
                      <div class="risk-score">
                        <div class="progress">
                          <div
                            class="progress-bar"
                            :class="riskScoreClass(student.risk_score)"
                            role="progressbar"
                            :style="{ width: `${student.risk_score * 100}%` }"
                            :aria-valuenow="student.risk_score * 100"
                            aria-valuemin="0"
                            aria-valuemax="100"
                          ></div>
                        </div>
                        <span>{{ (student.risk_score * 100).toFixed(0) }}%</span>
                      </div>
                    </td>
                    <td>{{ student.current_trimester }}</td>
                    <td>
                      <span
                        v-for="(factor, index) in student.key_factors"
                        :key="index"
                        class="factor-badge"
                      >
                        {{ factor }}
                      </span>
                    </td>
                    <td>
                      <button class="action-btn-small">
                        <i class="fas fa-envelope me-1"></i> Contact
                      </button>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
            <div v-else class="placeholder-content">
              <p>No at-risk students identified at this time.</p>
            </div>
          </div>
        </div>

        <!-- Course Performance Overview -->
        <div class="dashboard-card">
          <div class="card-header">
            <h2>
              <i class="fas fa-book me-2"></i> Course Performance
            </h2>
          </div>
          <div class="card-body">
            <div v-if="Object.keys(insights.dashboard_data?.courses || {}).length" class="table-responsive">
              <table class="dashboard-table">
                <thead>
                  <tr>
                    <th>Course</th>
                    <th>Pass Rate</th>
                    <th>Avg. Quiz 1</th>
                    <th>Avg. Quiz 2</th>
                    <th>Avg. Endterm</th>
                    <th>Attendance</th>
                    <th>Actions</th>
                  </tr>
                </thead>
                <tbody>
                  <tr v-for="(course, code) in insights.dashboard_data.courses" :key="code">
                    <td>{{ course.course_name }}</td>
                    <td>
                      <span :class="passRateClass(course.pass_rate)">
                        {{ course.pass_rate ? course.pass_rate.toFixed(1) + '%' : 'N/A' }}
                      </span>
                    </td>
                    <td>{{ course.avg_quiz1 ? course.avg_quiz1.toFixed(1) : 'N/A' }}</td>
                    <td>{{ course.avg_quiz2 ? course.avg_quiz2.toFixed(1) : 'N/A' }}</td>
                    <td>{{ course.avg_endterm ? course.avg_endterm.toFixed(1) : 'N/A' }}</td>
                    <td>{{ course.avg_attendance ? course.avg_attendance.toFixed(1) + '%' : 'N/A' }}</td>
                    <td>
                      <button class="action-btn-small" @click="viewCourseDetails(code)">
                        <i class="fas fa-chart-bar me-1"></i> Details
                      </button>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
            <div v-else class="placeholder-content">
              <p>No course data available.</p>
            </div>
          </div>
        </div>
      </div>
    </div>

    <footer class="dashboard-footer">
      Made with ❤️ by Dobby The Free-Elf
    </footer>
  </div>
</template>

<script>
import axios from 'axios';

export default {
  name: 'InstructorInsightsDashboard',
  data() {
    return {
      insights: {
        dashboard_data: {},
        narrative: ''
      },
      loading: true,
      error: null,
      isDarkMode: true
    };
  },
  computed: {
    formattedNarrative() {
      if (!this.insights.narrative) return [];
      return this.insights.narrative.split('\n\n').filter(p => p.trim());
    }
  },
  mounted() {
    this.fetchInsights();
  },
  methods: {
    async fetchInsights() {
      this.loading = true;
      this.error = null;

      const token = localStorage.getItem('authToken');

      if (!token) {
        this.error = "Authentication token not found. Please log in again.";
        this.loading = false;
        this.$router.push('/signin');
        return;
      }

      try {
        const response = await axios.get('http://127.0.0.1:3000/api/instructor/insights', {
          headers: {
            'Authorization': token
          }
        });
        
        this.insights = response.data;

      } catch (error) {
        console.error('Error fetching instructor insights:', error);

        if (error.response && error.response.status === 401) {
          this.error = 'Your session may have expired or is invalid. Please log in again.';
          localStorage.removeItem('authToken');
          localStorage.removeItem('userRole');
          localStorage.removeItem('userEmail');
          this.$router.push('/signin');
        } else {
          this.error = error.response?.data?.message || 'Failed to load insights. Please try again.';
        }

      } finally {
        this.loading = false;
      }
    },

    refreshData() {
      this.fetchInsights();
    },

    viewCourseDetails(courseCode) {
      const courseIdMatch = courseCode.match(/\d+/);
      const courseId = courseIdMatch ? courseIdMatch[0] : null;

      if (courseId) {
        this.$router.push(`/instructor/courses/${courseId}/insights`);
      } else {
        console.warn(`Could not extract ID from course code: ${courseCode}`);
      }
    },

    riskScoreClass(score) {
      if (score === null || score === undefined) return 'bg-secondary';
      if (score > 0.7) return 'bg-danger';
      if (score > 0.4) return 'bg-warning';
      return 'bg-success';
    },

    passRateClass(rate) {
      if (rate === null || rate === undefined) return '';
      if (rate < 75) return 'text-danger';
      if (rate < 90) return 'text-warning';
      return 'text-success';
    }
  }
};
</script>

<style scoped>
.dashboard-container {
  min-height: 100vh;
  padding: 2rem;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
}

/* Theme Variables */
.dark-mode {
  --background: #121212;
  --card-bg: rgba(255, 255, 255, 0.05);
  --card-border: rgba(255, 255, 255, 0.1);
  --text: #e1e1e1;
  --text-secondary: #a0a0a0;
  --primary: rgb(99, 102, 241);
  --primary-gradient: linear-gradient(to right, rgb(99, 102, 241), rgb(168, 85, 247));
  --danger: #ef4444;
  --warning: #f59e0b;
  --success: #10b981;
  --item-bg: rgba(255, 255, 255, 0.03);
  background-color: var(--background);
  color: var(--text);
}

.light-mode {
  --background: #f5f5f7;
  --card-bg: rgba(255, 255, 255, 0.9);
  --card-border: rgba(0, 0, 0, 0.1);
  --text: #333333;
  --text-secondary: #666666;
  --primary: rgb(99, 102, 241);
  --primary-gradient: linear-gradient(to right, rgb(99, 102, 241), rgb(168, 85, 247));
  --danger: #ef4444;
  --warning: #f59e0b;
  --success: #10b981;
  --item-bg: rgba(0, 0, 0, 0.03);
  background-color: var(--background);
  color: var(--text);
}

.dashboard-content {
  position: relative;
  z-index: 10;
  max-width: 1280px;
  margin: 0 auto;
}

/* Dashboard Header */
.dashboard-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 2rem;
}

.dashboard-title {
  font-size: clamp(1.5rem, 4vw, 2.5rem);
  margin-bottom: 0.5rem;
}

.title-regular {
  color: var(--text);
}

.title-fancy {
  font-family: 'Pacifico', cursive;
  background: var(--primary-gradient);
  -webkit-background-clip: text;
  color: transparent;
  margin-left: 0.5rem;
}

/* Loading Container */
.loading-container {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  padding: 50px 0;
}

.spinner-border {
  width: 3rem;
  height: 3rem;
  color: var(--primary);
}

/* Alert Container */
.alert-container {
  margin-bottom: 2rem;
}

.alert-message {
  padding: 1rem;
  background-color: rgba(239, 68, 68, 0.2);
  border-radius: 0.5rem;
  color: var(--danger);
}

/* Stats Grid */
.stats-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(240px, 1fr));
  gap: 1rem;
  margin-bottom: 2rem;
}

.stat-card {
  background: var(--card-bg);
  backdrop-filter: blur(10px);
  padding: 1.5rem;
  border-radius: 1rem;
  border: 1px solid var(--card-border);
  transition: transform 0.2s;
}

.stat-card:hover {
  transform: translateY(-5px);
  box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
}

.stat-value {
  font-size: 2rem;
  font-weight: bold;
  margin: 0.5rem 0;
  color: var(--primary);
}

.stat-trend {
  font-size: 0.9rem;
  color: var(--text-secondary);
}

.stat-trend.positive {
  color: var(--success);
}

/* Dashboard Cards */
.dashboard-main {
  display: flex;
  flex-direction: column;
  gap: 2rem;
}

.dashboard-card {
  background: var(--card-bg);
  backdrop-filter: blur(10px);
  padding: 1.5rem;
  border-radius: 1rem;
  border: 1px solid var(--card-border);
}

.card-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 1.5rem;
}

.card-header h2 {
  font-size: 1.5rem;
  margin: 0;
  display: flex;
  align-items: center;
}

.badge {
  padding: 0.25rem 0.75rem;
  background: var(--primary-gradient);
  color: white;
  border-radius: 1rem;
  font-size: 0.8rem;
}

.narrative-card {
  border-left: 4px solid var(--primary);
}

.narrative-paragraph {
  margin-bottom: 15px;
  line-height: 1.6;
}

.placeholder-content {
  padding: 1.5rem;
  text-align: center;
  color: var(--text-secondary);
}

/* Tables */
.table-responsive {
  overflow-x: auto;
}

.dashboard-table {
  width: 100%;
  border-collapse: collapse;
}

.dashboard-table th,
.dashboard-table td {
  padding: 1rem;
  text-align: left;
  border-bottom: 1px solid var(--card-border);
}

.dashboard-table th {
  font-weight: bold;
  color: var(--text-secondary);
}

.dashboard-table tr:hover {
  background: var(--item-bg);
}

/* Risk Score */
.risk-score {
  display: flex;
  align-items: center;
  gap: 0.5rem;
}

.progress {
  flex-grow: 1;
  height: 8px;
  background-color: var(--item-bg);
  border-radius: 4px;
  overflow: hidden;
}

.progress-bar {
  height: 100%;
}

.bg-danger {
  background-color: var(--danger);
}

.bg-warning {
  background-color: var(--warning);
}

.bg-success {
  background-color: var(--success);
}

.bg-secondary {
  background-color: var(--text-secondary);
}

.text-danger {
  color: var(--danger);
}

.text-warning {
  color: var(--warning);
}

.text-success {
  color: var(--success);
}

/* Badges for factors */
.factor-badge {
  display: inline-block;
  padding: 0.25rem 0.5rem;
  margin: 0.25rem;
  background-color: rgba(245, 158, 11, 0.2);
  color: var(--warning);
  border-radius: 0.25rem;
  font-size: 0.8rem;
}

/* Buttons */
.action-btn {
  padding: 0.5rem 1.5rem;
  background: var(--primary-gradient);
  border: none;
  border-radius: 0.5rem;
  color: white;
  cursor: pointer;
  font-weight: 500;
  display: flex;
  align-items: center;
  transition: transform 0.2s, box-shadow 0.2s;
}

.action-btn:hover {
  transform: translateY(-2px);
  box-shadow: 0 4px 12px rgba(99, 102, 241, 0.3);
}

.action-btn-small {
  padding: 0.5rem 1rem;
  background-color: rgba(99, 102, 241, 0.2);
  border: none;
  border-radius: 0.5rem;
  color: var(--primary);
  cursor: pointer;
  font-size: 0.9rem;
  transition: background-color 0.2s;
}

.action-btn-small:hover {
  background-color: rgba(99, 102, 241, 0.3);
}

/* Footer */
.dashboard-footer {
  text-align: center;
  padding: 2rem 0 1rem;
  font-size: 0.9rem;
  color: var(--text-secondary);
  margin-top: 2rem;
}

/* Responsive Adjustments */
@media (max-width: 768px) {
  .dashboard-container {
    padding: 1rem;
  }

  .dashboard-header {
    flex-direction: column;
    align-items: flex-start;
    gap: 1rem;
  }

  .header-actions {
    width: 100%;
  }

  .action-btn {
    width: 100%;
    justify-content: center;
  }
}
</style>