<template>
    <div class="student-insights-dashboard">
      <div class="page-header">
        <h1>Your Academic Insights</h1>
        <div class="header-actions">
          <button class="btn btn-primary" @click="refreshData">
            <i class="fas fa-sync-alt"></i> Refresh
          </button>
        </div>
      </div>
  
      <!-- Loading State -->
      <div v-if="loading" class="loading-container">
        <div class="spinner-border text-primary" role="status">
          <span class="visually-hidden">Loading...</span>
        </div>
        <p>Analyzing your academic data...</p>
      </div>
  
      <!-- Error State -->
      <div v-if="error" class="alert alert-danger">
        <strong>Error:</strong> {{ error }}
      </div>
  
      <!-- Dashboard Content -->
      <div v-if="!loading && !error" class="dashboard-content">
        <!-- Student Summary Card -->
        <div class="card student-summary-card mb-4">
          <div class="card-body">
            <div class="row">
              <div class="col-md-8">
                <h2>{{ insights.student_data?.name }}</h2>
                <p class="text-muted">Student ID: {{ insights.student_data?.student_id }}</p>
                <div class="student-stats">
                  <div class="stat-item">
                    <span class="stat-label">Current Trimester</span>
                    <span class="stat-value">{{ insights.student_data?.current_trimester }}</span>
                  </div>
                  <div class="stat-item">
                    <span class="stat-label">CGPA</span>
                    <span class="stat-value">{{ insights.student_data?.cgpa }}</span>
                  </div>
                  <div class="stat-item">
                    <span class="stat-label">Performance Trend</span>
                    <span class="stat-value trend-badge" :class="trendClass">
                      {{ insights.student_data?.performance_trend }}
                      <i :class="trendIcon"></i>
                    </span>
                  </div>
                </div>
              </div>
              <div class="col-md-4 text-center d-flex align-items-center justify-content-center">
                <div class="progress-circular">
                  <svg viewBox="0 0 36 36" class="circular-chart">
                    <path class="circle-bg" d="M18 2.0845
                      a 15.9155 15.9155 0 0 1 0 31.831
                      a 15.9155 15.9155 0 0 1 0 -31.831" />
                    <path
                      class="circle"
                      :class="gpaColorClass"
                      :stroke-dasharray="`${gpaPercentage}, 100`"
                      d="M18 2.0845
                        a 15.9155 15.9155 0 0 1 0 31.831
                        a 15.9155 15.9155 0 0 1 0 -31.831"
                    />
                    <text x="18" y="20.35" class="percentage">{{ insights.student_data?.cgpa }}</text>
                  </svg>
                  <div class="progress-label">CGPA</div>
                </div>
              </div>
            </div>
          </div>
        </div>
  
        <!-- AI-Generated Narrative Card -->
        <div class="card narrative-card mb-4">
          <div class="card-header d-flex justify-content-between align-items-center">
            <h2 class="m-0">
              <i class="fas fa-robot me-2"></i> Your Personalized Academic Insights
            </h2>
            <span class="badge bg-primary">Generated by Gemini</span>
          </div>
          <div class="card-body">
            <div v-if="insights.narrative" class="narrative-content">
              <p v-for="(paragraph, index) in formattedNarrative" :key="index" class="narrative-paragraph">
                {{ paragraph }}
              </p>
            </div>
            <div v-else class="placeholder-content">
              <p>No narrative available. Try refreshing the data.</p>
            </div>
          </div>
        </div>
  
        <!-- Current Courses -->
        <div class="card mb-4">
          <div class="card-header">
            <h2>
              <i class="fas fa-book-open me-2"></i> Current Courses
            </h2>
          </div>
          <div class="card-body">
            <div v-if="insights.student_data?.ongoing_courses?.length" class="table-responsive">
              <table class="table">
                <thead>
                  <tr>
                    <th>Course</th>
                    <th>Quiz 1</th>
                    <th>Quiz 2</th>
                    <th>Attendance</th>
                    <th>Progress</th>
                    <th>Actions</th>
                  </tr>
                </thead>
                <tbody>
                  <tr v-for="course in insights.student_data.ongoing_courses" :key="course.course_code">
                    <td>
                      <strong>{{ course.course_name }}</strong>
                      <div class="text-muted">{{ course.course_code }}</div>
                    </td>
                    <td>{{ course.quiz1 ? course.quiz1.toFixed(1) : 'Pending' }}</td>
                    <td>{{ course.quiz2 ? course.quiz2.toFixed(1) : 'Pending' }}</td>
                    <td>
                      <div class="d-flex align-items-center">
                        <div class="progress flex-grow-1 me-2" style="height: 8px;">
                          <div
                            class="progress-bar"
                            :class="attendanceColorClass(course.attendance_percentage)"
                            role="progressbar"
                            :style="{ width: `${course.attendance_percentage}%` }"
                          ></div>
                        </div>
                        <span>{{ course.attendance_percentage ? course.attendance_percentage.toFixed(1) + '%' : 'N/A' }}</span>
                      </div>
                    </td>
                    <td>
                      <!-- Simple progress estimation based on available data -->
                      <div class="progress">
                        <div
                          class="progress-bar bg-info"
                          role="progressbar"
                          :style="{ width: `${calculateCourseProgress(course)}%` }"
                        ></div>
                      </div>
                    </td>
                    <td>
                      <button class="btn btn-sm btn-outline-primary" @click="viewCourseComparison(course.course_code)">
                        <i class="fas fa-chart-bar me-1"></i> Compare
                      </button>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
            <div v-else class="placeholder-content">
              <p>You are not currently enrolled in any courses.</p>
            </div>
          </div>
        </div>
  
        <!-- Performance History -->
        <div class="card mb-4">
          <div class="card-header">
            <h2>
              <i class="fas fa-history me-2"></i> Performance History
            </h2>
          </div>
          <div class="card-body">
            <div v-if="insights.student_data?.completed_courses?.length" class="completed-courses">
              <div class="table-responsive">
                <table class="table">
                  <thead>
                    <tr>
                      <th>Course</th>
                      <th>Trimester</th>
                      <th>Grade</th>
                      <th>Score</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr v-for="course in insights.student_data.completed_courses" :key="course.course_code">
                      <td>
                        <strong>{{ course.course_name }}</strong>
                        <div class="text-muted">{{ course.course_code }}</div>
                      </td>
                      <td>{{ course.trimester }}</td>
                      <td>
                        <span class="grade-badge" :class="gradeColorClass(course.grade)">
                          {{ course.grade }}
                        </span>
                      </td>
                      <td>{{ course.total_score ? course.total_score.toFixed(1) : 'N/A' }}</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
            <div v-else class="placeholder-content">
              <p>You have not completed any courses yet.</p>
            </div>
          </div>
        </div>
  
        <!-- Course Recommendations -->
        <div class="card recommendation-card">
          <div class="card-header">
            <h2>
              <i class="fas fa-lightbulb me-2"></i> Course Recommendations
            </h2>
          </div>
          <div class="card-body">
            <button class="btn btn-outline-primary mb-3" @click="fetchRecommendations" :disabled="loadingRecommendations">
              <i class="fas fa-magic me-1"></i>
              {{ loadingRecommendations ? 'Generating Recommendations...' : 'Get AI Recommendations' }}
            </button>
            
            <div v-if="recommendations" class="recommendation-content">
              <p v-for="(paragraph, index) in formattedRecommendations" :key="index" class="recommendation-paragraph">
                {{ paragraph }}
              </p>
            </div>
            <div v-else-if="!loadingRecommendations" class="placeholder-content">
              <p>Click the button above to get personalized course recommendations based on your performance.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </template>
  
  <script>
  import axios from 'axios';
  
  export default {
    name: 'StudentInsightsDashboard',
    data() {
      return {
        insights: {
          student_data: {},
          narrative: ''
        },
        recommendations: null,
        loading: true,
        loadingRecommendations: false,
        error: null
      };
    },
    computed: {
      formattedNarrative() {
        if (!this.insights.narrative) return [];
        return this.insights.narrative.split('\n\n').filter(p => p.trim());
      },
      
      formattedRecommendations() {
        if (!this.recommendations) return [];
        return this.recommendations.split('\n\n').filter(p => p.trim());
      },
      
      gpaPercentage() {
        const cgpa = this.insights.student_data?.cgpa || 0;
        // Convert CGPA (0-10 scale) to percentage (0-100)
        return (cgpa / 10) * 100;
      },
      
      gpaColorClass() {
        const cgpa = this.insights.student_data?.cgpa || 0;
        if (cgpa >= 8) return 'success';
        if (cgpa >= 6) return 'warning';
        return 'danger';
      },
      
      trendClass() {
        const trend = this.insights.student_data?.performance_trend || '';
        if (trend.toLowerCase() === 'improving') return 'trend-up';
        if (trend.toLowerCase() === 'declining') return 'trend-down';
        return 'trend-stable';
      },
      
      trendIcon() {
        const trend = this.insights.student_data?.performance_trend || '';
        if (trend.toLowerCase() === 'improving') return 'fas fa-arrow-up';
        if (trend.toLowerCase() === 'declining') return 'fas fa-arrow-down';
        return 'fas fa-equals';
      }
    },
    mounted() {
      this.fetchInsights();
    },
    methods: {
      async fetchInsights() {
        this.loading = true;
        this.error = null;
        
        try {
          const response = await axios.get('/api/student/insights', {
            headers: {
              'Authorization': `Bearer ${this.$store.state.auth.token}`
            }
          });
          
          this.insights = response.data;
        } catch (error) {
          console.error('Error fetching student insights:', error);
          this.error = error.response?.data?.message || 'Failed to load insights. Please try again.';
        } finally {
          this.loading = false;
        }
      },
      
      async fetchRecommendations() {
        this.loadingRecommendations = true;
        
        try {
          const response = await axios.get('/api/student/recommendations', {
            headers: {
              'Authorization': `Bearer ${this.$store.state.auth.token}`
            }
          });
          
          this.recommendations = response.data.recommendations;
        } catch (error) {
          console.error('Error fetching recommendations:', error);
          this.$toast.error('Failed to generate recommendations. Please try again.');
        } finally {
          this.loadingRecommendations = false;
        }
      },
      
      refreshData() {
        this.fetchInsights();
        this.recommendations = null;
      },
      
      viewCourseComparison(courseCode) {
        // Get the course ID from the code (in a real app, you'd use a proper mapping)
        const courseId = courseCode.replace(/[^0-9]/g, '');
        this.$router.push(`/student/courses/${courseId}/comparison`);
      },
      
      calculateCourseProgress(course) {
        // Simple estimation: 25% for first assignment, 50% for Quiz 1, 75% for assignments 1-6, 100% if all done
        if (course.endterm) return 100;
        if (course.quiz2) return 90;
        if (course.assignment6) return 75;
        if (course.quiz1) return 50;
        if (course.assignment1) return 25;
        return 10; // Just started
      },
      
      attendanceColorClass(percentage) {
        if (!percentage) return 'bg-secondary';
        if (percentage < 75) return 'bg-danger';
        if (percentage < 85) return 'bg-warning';
        return 'bg-success';
      },
      
      gradeColorClass(grade) {
        if (!grade) return '';
        if (grade === 'A') return 'grade-a';
        if (grade === 'B') return 'grade-b';
        if (grade === 'C') return 'grade-c';
        if (grade === 'D') return 'grade-d';
        return 'grade-f';
      }
    }
  };
  </script>
  
  <style scoped>
  .student-insights-dashboard {
    padding: 20px;
  }
  
  .page-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 20px;
  }
  
  .loading-container {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    padding: 50px 0;
  }
  
  .student-summary-card {
    background: linear-gradient(to right, #f5f7fa, #c3cfe2);
    border: none;
  }
  
  .student-stats {
    display: flex;
    flex-wrap: wrap;
    gap: 20px;
    margin-top: 15px;
  }
  
  .stat-item {
    display: flex;
    flex-direction: column;
  }
  
  .stat-label {
    font-size: 0.9rem;
    color: #6c757d;
  }
  
  .stat-value {
    font-size: 1.2rem;
    font-weight: bold;
  }
  
  .trend-badge {
    display: inline-flex;
    align-items: center;
    gap: 5px;
    padding: 3px 8px;
    border-radius: 4px;
  }
  
  .trend-up {
    background-color: rgba(40, 167, 69, 0.2);
    color: #28a745;
  }
  
  .trend-down {
    background-color: rgba(220, 53, 69, 0.2);
    color: #dc3545;
  }
  
  .trend-stable {
    background-color: rgba(108, 117, 125, 0.2);
    color: #6c757d;
  }
  
  .narrative-card {
    border-left: 4px solid #4285f4;
  }
  
  .narrative-paragraph, .recommendation-paragraph {
    margin-bottom: 15px;
    line-height: 1.6;
  }
  
  .grade-badge {
    display: inline-block;
    width: 30px;
    height: 30px;
    line-height: 30px;
    text-align: center;
    border-radius: 50%;
    font-weight: bold;
  }
  
  .grade-a {
    background-color: #28a745;
    color: white;
  }
  
  .grade-b {
    background-color: #17a2b8;
    color: white;
  }
  
  .grade-c {
    background-color: #ffc107;
    color: black;
  }
  
  .grade-d {
    background-color: #fd7e14;
    color: white;
  }
  
  .grade-f {
    background-color: #dc3545;
    color: white;
  }
  
  .recommendation-card {
    border-left: 4px solid #17a2b8;
  }
  
  .placeholder-content {
    padding: 20px;
    text-align: center;
    color: #6c757d;
  }
  
  /* Progress circular chart */
  .progress-circular {
    width: 150px;
    margin: 0 auto;
  }
  
  .circular-chart {
    width: 100%;
    height: auto;
  }
  
  .circle-bg {
    fill: none;
    stroke: #eee;
    stroke-width: 3.8;
  }
  
  .circle {
    fill: none;
    stroke-width: 2.8;
    stroke-linecap: round;
    animation: progress 1s ease-out forwards;
  }
  
  .circle.success {
    stroke: #28a745;
  }
  
  .circle.warning {
    stroke: #ffc107;
  }
  
  .circle.danger {
    stroke: #dc3545;
  }
  
  .percentage {
    fill: #111;
    font-family: sans-serif;
    font-size: 0.5em;
    text-anchor: middle;
    font-weight: bold;
  }
  
  .progress-label {
    text-align: center;
    margin-top: 5px;
    font-weight: bold;
    color: #555;
  }
  
  @keyframes progress {
    0% {
      stroke-dasharray: 0 100;
    }
  }
  </style>