<template>
  <div class="dashboard-container">
    <div class="dashboard-content">
      <!-- Dashboard Header -->
      <div class="dashboard-header">
        <h1 class="dashboard-title">
          <span class="title-regular">Your</span>
          <span class="title-fancy">Academic Insights</span>
        </h1>
        <p class="dashboard-subtitle">Track your performance and get personalized recommendations</p>
      </div>

      <!-- Loading State -->
      <div v-if="loading" class="loading-container">
        <div class="spinner"></div>
        <p>Analyzing your academic data...</p>
      </div>

      <!-- Error State -->
      <div v-if="error" class="alert alert-danger">
        <strong>Error:</strong> {{ error }}
      </div>

      <!-- Dashboard Content -->
      <div v-if="!loading && !error" class="dashboard-content">
        <!-- Student Summary Stats -->
        <div class="stats-grid">
          <div class="stat-card">
            <div class="stat-header">
              <h3>CGPA</h3>
              <div class="refresh-action">
                <button class="refresh-btn" @click="refreshData">
                  <i class="fas fa-sync-alt"></i>
                </button>
              </div>
            </div>
            <div class="stat-value">{{ insights.student_data?.cgpa || 'N/A' }}</div>
            <div class="circular-progress">
              <svg viewBox="0 0 36 36" class="circular-chart">
                <path class="circle-bg" d="M18 2.0845
                  a 15.9155 15.9155 0 0 1 0 31.831
                  a 15.9155 15.9155 0 0 1 0 -31.831" />
                <path
                  class="circle"
                  :class="gpaColorClass"
                  :stroke-dasharray="`${gpaPercentage}, 100`"
                  d="M18 2.0845
                    a 15.9155 15.9155 0 0 1 0 31.831
                    a 15.9155 15.9155 0 0 1 0 -31.831"
                />
              </svg>
            </div>
          </div>
          
          <div class="stat-card">
            <h3>Current Trimester</h3>
            <div class="stat-value">{{ insights.student_data?.current_trimester || 'N/A' }}</div>
            <div class="stat-info">
              <span class="student-id">ID: {{ insights.student_data?.student_id || 'N/A' }}</span>
            </div>
          </div>
          
          <div class="stat-card">
            <h3>Performance Trend</h3>
            <div class="stat-value">
              <span class="trend-badge" :class="trendClass">
                {{ insights.student_data?.performance_trend || 'N/A' }}
                <i :class="trendIcon"></i>
              </span>
            </div>
            <div class="stat-trend" :class="{'positive': trendClass === 'trend-up'}">
              {{ getTrendDescription() }}
            </div>
          </div>
          
          <div class="stat-card">
            <h3>Attendance</h3>
            <div class="stat-value">{{ calculateAverageAttendance() }}%</div>
            <div class="progress-bar">
              <div class="progress-fill" :style="{width: `${calculateAverageAttendance()}%`}"></div>
            </div>
          </div>
        </div>

        <!-- Dashboard Grid -->
        <div class="dashboard-grid">
          <!-- AI-Generated Narrative Card -->
          <div class="dashboard-card narrative-card">
            <div class="card-header">
              <h2>
                <i class="fas fa-robot"></i> Your Personalized Insights
              </h2>
              <span class="ai-badge">Generated by Gemini</span>
            </div>
            <div class="card-body">
              <div v-if="insights.narrative" class="narrative-content">
                <p v-for="(paragraph, index) in formattedNarrative" :key="index" class="narrative-paragraph">
                  {{ paragraph }}
                </p>
              </div>
              <div v-else class="placeholder-content">
                <p>No narrative available. Try refreshing the data.</p>
              </div>
            </div>
          </div>

          <!-- Current Courses Card -->
          <div class="dashboard-card">
            <div class="card-header">
              <h2>
                <i class="fas fa-book-open"></i> Current Courses
              </h2>
              <button class="view-all-btn">View All</button>
            </div>
            <div class="card-body">
              <div v-if="insights.student_data?.ongoing_courses?.length" class="course-list">
                <div v-for="course in insights.student_data.ongoing_courses" :key="course.course_code" class="course-item">
                  <div class="course-info">
                    <h3>{{ course.course_name }}</h3>
                    <p class="course-code">{{ course.course_code }}</p>
                  </div>
                  <div class="course-progress">
                    <div class="progress-bar">
                      <div class="progress-fill" :style="{width: `${calculateCourseProgress(course)}%`}"></div>
                    </div>
                    <span class="progress-percentage">{{ calculateCourseProgress(course) }}%</span>
                  </div>
                  <div class="course-stats">
                    <div class="course-stat">
                      <span class="stat-label">Quiz 1</span>
                      <span class="stat-value">{{ course.quiz1 ? course.quiz1.toFixed(1) : 'Pending' }}</span>
                    </div>
                    <div class="course-stat">
                      <span class="stat-label">Quiz 2</span>
                      <span class="stat-value">{{ course.quiz2 ? course.quiz2.toFixed(1) : 'Pending' }}</span>
                    </div>
                    <div class="course-stat">
                      <span class="stat-label">Attendance</span>
                      <span class="stat-value" :class="attendanceColorClass(course.attendance_percentage)">
                        {{ course.attendance_percentage ? course.attendance_percentage.toFixed(1) + '%' : 'N/A' }}
                      </span>
                    </div>
                  </div>
                  <button class="action-btn" @click="viewCourseComparison(course.course_code)">
                    <i class="fas fa-chart-bar"></i> Compare
                  </button>
                </div>
              </div>
              <div v-else class="placeholder-content">
                <p>You are not currently enrolled in any courses.</p>
              </div>
            </div>
          </div>

          <!-- Performance History Card -->
          <div class="dashboard-card">
            <div class="card-header">
              <h2>
                <i class="fas fa-history"></i> Performance History
              </h2>
              <button class="view-all-btn">View All</button>
            </div>
            <div class="card-body">
              <div v-if="insights.student_data?.completed_courses?.length" class="history-content">
                <div v-for="course in insights.student_data.completed_courses" :key="course.course_code" class="history-item">
                  <div class="history-info">
                    <h3>{{ course.course_name }}</h3>
                    <p class="course-code">{{ course.course_code }}</p>
                  </div>
                  <div class="history-data">
                    <div class="trimester-badge">{{ course.trimester }}</div>
                    <div class="grade-badge" :class="gradeColorClass(course.grade)">
                      {{ course.grade }}
                    </div>
                    <div class="score-display">
                      {{ course.total_score ? course.total_score.toFixed(1) : 'N/A' }}
                    </div>
                  </div>
                </div>
              </div>
              <div v-else class="placeholder-content">
                <p>You have not completed any courses yet.</p>
              </div>
            </div>
          </div>

          <!-- Course Recommendations Card -->
          <div class="dashboard-card recommendation-card">
            <div class="card-header">
              <h2>
                <i class="fas fa-lightbulb"></i> Course Recommendations
              </h2>
            </div>
            <div class="card-body">
              <button class="recommendation-btn" @click="fetchRecommendations" :disabled="loadingRecommendations">
                <i class="fas fa-magic"></i>
                {{ loadingRecommendations ? 'Generating Recommendations...' : 'Get AI Recommendations' }}
              </button>
              
              <div v-if="recommendations" class="recommendations-list">
                <div v-for="(paragraph, index) in formattedRecommendations" :key="index" class="recommendation-item">
                  {{ paragraph }}
                </div>
              </div>
              <div v-else-if="!loadingRecommendations" class="placeholder-content">
                <p>Click the button above to get personalized course recommendations based on your performance.</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import axios from 'axios';

export default {
  name: 'StudentInsightsDashboard',
  data() {
    return {
      insights: {
        student_data: {},
        narrative: ''
      },
      recommendations: null,
      loading: true,
      loadingRecommendations: false,
      error: null
    };
  },
  computed: {
    formattedNarrative() {
      if (!this.insights.narrative) return [];
      return this.insights.narrative.split('\n\n').filter(p => p.trim());
    },
    
    formattedRecommendations() {
      if (!this.recommendations) return [];
      return this.recommendations.split('\n\n').filter(p => p.trim());
    },
    
    gpaPercentage() {
      const cgpa = this.insights.student_data?.cgpa || 0;
      // Convert CGPA (0-10 scale) to percentage (0-100)
      return (cgpa / 10) * 100;
    },
    
    gpaColorClass() {
      const cgpa = this.insights.student_data?.cgpa || 0;
      if (cgpa >= 8) return 'success';
      if (cgpa >= 6) return 'warning';
      return 'danger';
    },
    
    trendClass() {
      const trend = this.insights.student_data?.performance_trend || '';
      if (trend.toLowerCase() === 'improving') return 'trend-up';
      if (trend.toLowerCase() === 'declining') return 'trend-down';
      return 'trend-stable';
    },
    
    trendIcon() {
      const trend = this.insights.student_data?.performance_trend || '';
      if (trend.toLowerCase() === 'improving') return 'fas fa-arrow-up';
      if (trend.toLowerCase() === 'declining') return 'fas fa-arrow-down';
      return 'fas fa-equals';
    }
  },
  mounted() {
    this.fetchInsights();
  },
  methods: {
    async fetchInsights() {
      this.loading = true;
      this.error = null;
      
      try {
        const response = await axios.get('http://127.0.0.1:3000/api/student/insights', {
          headers: {
            'Authorization': `Bearer ${this.$store.state.authToken}`
          }
        });
        
        this.insights = response.data;
      } catch (error) {
        console.error('Error fetching student insights:', error);
        this.error = error.response?.data?.message || 'Failed to load insights. Please try again.';
      } finally {
        this.loading = false;
      }
    },
    
    async fetchRecommendations() {
      this.loadingRecommendations = true;
      
      try {
        const response = await axios.get('http://127.0.0.1:3000/api/student/recommendations', {
          headers: {
            'Authorization': `Bearer ${this.$store.state.auth.token}`
          }
        });
        
        this.recommendations = response.data.recommendations;
      } catch (error) {
        console.error('Error fetching recommendations:', error);
        this.$toast.error('Failed to generate recommendations. Please try again.');
      } finally {
        this.loadingRecommendations = false;
      }
    },
    
    refreshData() {
      this.fetchInsights();
      this.recommendations = null;
    },
    
    viewCourseComparison(courseCode) {
      // Get the course ID from the code (in a real app, you'd use a proper mapping)
      const courseId = courseCode.replace(/[^0-9]/g, '');
      this.$router.push(`/student/courses/${courseId}/comparison`);
    },
    
    calculateCourseProgress(course) {
      // Simple estimation: 25% for first assignment, 50% for Quiz 1, 75% for assignments 1-6, 100% if all done
      if (course.endterm) return 100;
      if (course.quiz2) return 90;
      if (course.assignment6) return 75;
      if (course.quiz1) return 50;
      if (course.assignment1) return 25;
      return 10; // Just started
    },
    
    attendanceColorClass(percentage) {
      if (!percentage) return 'attendance-na';
      if (percentage < 75) return 'attendance-danger';
      if (percentage < 85) return 'attendance-warning';
      return 'attendance-success';
    },
    
    gradeColorClass(grade) {
      if (!grade) return '';
      if (grade === 'A') return 'grade-a';
      if (grade === 'B') return 'grade-b';
      if (grade === 'C') return 'grade-c';
      if (grade === 'D') return 'grade-d';
      return 'grade-f';
    },

    calculateAverageAttendance() {
      const courses = this.insights.student_data?.ongoing_courses || [];
      if (!courses.length) return 0;
      
      const totalAttendance = courses.reduce((sum, course) => {
        return sum + (course.attendance_percentage || 0);
      }, 0);
      
      return Math.round(totalAttendance / courses.length);
    },
    
    getTrendDescription() {
      const trend = this.insights.student_data?.performance_trend || '';
      if (trend.toLowerCase() === 'improving') return 'Keep up the good work!';
      if (trend.toLowerCase() === 'declining') return 'Needs attention';
      return 'Maintaining consistent performance';
    }
  }
};
</script>

<style scoped>
.dashboard-container {
  min-height: 100vh;
  padding: 2rem;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
  background: linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%);
  color: #333;
}

.dashboard-content {
  position: relative;
  z-index: 10;
  max-width: 1280px;
  margin: 0 auto;
}

.dashboard-header {
  margin-bottom: 2rem;
}

.dashboard-title {
  font-size: clamp(1.5rem, 4vw, 2.5rem);
  margin-bottom: 0.5rem;
}

.title-regular {
  color: #333;
}

.title-fancy {
  font-family: 'Segoe UI', Roboto, sans-serif;
  background: linear-gradient(to right, #4285f4, #34a853);
  -webkit-background-clip: text;
  color: transparent;
  margin-left: 8px;
}

.dashboard-subtitle {
  color: #6c757d;
  font-size: 1rem;
}

/* Loading */
.loading-container {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  padding: 50px 0;
}

.spinner {
  width: 50px;
  height: 50px;
  border: 5px solid rgba(0, 0, 0, 0.1);
  border-radius: 50%;
  border-top-color: #4285f4;
  animation: spin 1s ease-in-out infinite;
}

@keyframes spin {
  to { transform: rotate(360deg); }
}

/* Stats Grid */
.stats-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(240px, 1fr));
  gap: 1.5rem;
  margin-bottom: 2rem;
}

.stat-card {
  background: white;
  padding: 1.5rem;
  border-radius: 1rem;
  box-shadow: 0 4px 15px rgba(0, 0, 0, 0.05);
  transition: transform 0.3s ease, box-shadow 0.3s ease;
  position: relative;
  overflow: hidden;
}

.stat-card:hover {
  transform: translateY(-5px);
  box-shadow: 0 8px 20px rgba(0, 0, 0, 0.1);
}

.stat-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.refresh-btn {
  background: none;
  border: none;
  color: #4285f4;
  cursor: pointer;
  transition: transform 0.3s ease;
}

.refresh-btn:hover {
  transform: rotate(180deg);
}

.stat-card h3 {
  color: #6c757d;
  font-size: 1rem;
  margin-top: 0;
  margin-bottom: 0.5rem;
}

.stat-value {
  font-size: 2rem;
  font-weight: bold;
  margin: 0.5rem 0;
  color: #333;
}

.student-id {
  font-size: 0.9rem;
  color: #6c757d;
}

.circular-progress {
  margin-top: 0.5rem;
}

.circular-chart {
  width: 80px;
  height: 80px;
}

.circle-bg {
  fill: none;
  stroke: #eee;
  stroke-width: 3.8;
}

.circle {
  fill: none;
  stroke-width: 2.8;
  stroke-linecap: round;
  animation: progress 1s ease-out forwards;
}

.circle.success {
  stroke: #34a853;
}

.circle.warning {
  stroke: #fbbc05;
}

.circle.danger {
  stroke: #ea4335;
}

@keyframes progress {
  0% { stroke-dasharray: 0 100; }
}

.trend-badge {
  display: inline-flex;
  align-items: center;
  gap: 5px;
  padding: 6px 12px;
  border-radius: 20px;
  font-size: 1rem;
}

.trend-up {
  background-color: rgba(52, 168, 83, 0.15);
  color: #34a853;
}

.trend-down {
  background-color: rgba(234, 67, 53, 0.15);
  color: #ea4335;
}

.trend-stable {
  background-color: rgba(251, 188, 5, 0.15);
  color: #fbbc05;
}

.stat-trend {
  font-size: 0.9rem;
  color: #6c757d;
  margin-top: 0.5rem;
}

.stat-trend.positive {
  color: #34a853;
}

.progress-bar {
  width: 100%;
  height: 8px;
  background: rgba(66, 133, 244, 0.1);
  border-radius: 4px;
  margin-top: 0.8rem;
  overflow: hidden;
}

.progress-fill {
  height: 100%;
  background: linear-gradient(to right, #4285f4, #34a853);
  border-radius: 4px;
  transition: width 0.3s ease;
}

/* Dashboard Grid */
.dashboard-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(400px, 1fr));
  gap: 1.5rem;
}

.dashboard-card {
  background: white;
  padding: 1.5rem;
  border-radius: 1rem;
  box-shadow: 0 4px 15px rgba(0, 0, 0, 0.05);
  transition: transform 0.3s ease, box-shadow 0.3s ease;
}

.dashboard-card:hover {
  transform: translateY(-5px);
  box-shadow: 0 8px 20px rgba(0, 0, 0, 0.1);
}

.card-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 1.5rem;
  padding-bottom: 0.75rem;
  border-bottom: 1px solid rgba(0, 0, 0, 0.05);
}

.card-header h2 {
  font-size: 1.25rem;
  margin: 0;
  display: flex;
  align-items: center;
  gap: 0.5rem;
}

.card-header h2 i {
  color: #4285f4;
}

.view-all-btn {
  color: #4285f4;
  background: none;
  border: none;
  cursor: pointer;
  font-size: 0.9rem;
  transition: color 0.3s ease;
}

.view-all-btn:hover {
  color: #34a853;
  text-decoration: underline;
}

/* Narrative Card */
.narrative-card {
  border-left: 4px solid #4285f4;
}

.ai-badge {
  background: linear-gradient(to right, #4285f4, #34a853);
  color: white;
  padding: 4px 10px;
  border-radius: 12px;
  font-size: 0.8rem;
  font-weight: bold;
}

.narrative-paragraph {
  margin-bottom: 15px;
  line-height: 1.6;
  color: #333;
}

/* Course List */
.course-list {
  display: flex;
  flex-direction: column;
  gap: 1.25rem;
}

.course-item {
  background: rgba(66, 133, 244, 0.03);
  border-radius: 0.75rem;
  padding: 1rem;
  transition: background 0.3s ease;
}

.course-item:hover {
  background: rgba(66, 133, 244, 0.07);
}

.course-info h3 {
  margin: 0 0 0.25rem 0;
  font-size: 1.1rem;
}

.course-code {
  margin: 0;
  color: #6c757d;
  font-size: 0.9rem;
}

.course-progress {
  margin: 0.75rem 0;
  display: flex;
  align-items: center;
  gap: 0.5rem;
}

.progress-percentage {
  font-size: 0.9rem;
  font-weight: bold;
  color: #4285f4;
}

.course-stats {
  display: flex;
  flex-wrap: wrap;
  gap: 1rem;
  margin: 0.5rem 0;
}

.course-stat {
  display: flex;
  flex-direction: column;
  min-width: 80px;
}

.stat-label {
  font-size: 0.8rem;
  color: #6c757d;
}

.stat-value {
  font-size: 1rem;
  font-weight: bold;
}

.attendance-danger {
  color: #ea4335;
}

.attendance-warning {
  color: #fbbc05;
}

.attendance-success {
  color: #34a853;
}

.attendance-na {
  color: #6c757d;
}

.action-btn {
  margin-top: 0.75rem;
  padding: 0.5rem 1rem;
  background: linear-gradient(to right, #4285f4, #34a853);
  border: none;
  border-radius: 0.5rem;
  color: white;
  cursor: pointer;
  font-size: 0.9rem;
  display: flex;
  align-items: center;
  gap: 0.5rem;
  transition: transform 0.3s ease;
}

.action-btn:hover {
  transform: translateY(-2px);
}

/* History List */
.history-content {
  display: flex;
  flex-direction: column;
  gap: 1rem;
}

.history-item {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 0.75rem;
  background: rgba(66, 133, 244, 0.03);
  border-radius: 0.5rem;
  transition: background 0.3s ease;
}

.history-item:hover {
  background: rgba(66, 133, 244, 0.07);
}

.history-info h3 {
  margin: 0 0 0.25rem 0;
  font-size: 1rem;
}

.history-data {
  display: flex;
  align-items: center;
  gap: 1rem;
}

.trimester-badge {
  padding: 4px 8px;
  background: rgba(66, 133, 244, 0.1);
  color: #4285f4;
  border-radius: 4px;
  font-size: 0.8rem;
}

.grade-badge {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 32px;
  height: 32px;
  border-radius: 50%;
  font-weight: bold;
  font-size: 0.9rem;
}

.grade-a {
  background-color: #34a853;
  color: white;
}

.grade-b {
  background-color: #4285f4;
  color: white;
}

.grade-c {
  background-color: #fbbc05;
  color: black;
}

.grade-d {
  background-color: #ff6d01;
  color: white;
}

.grade-f {
  background-color: #ea4335;
  color: white;
}

.score-display {
  font-weight: bold;
}

/* Recommendations */
.recommendation-card {
  border-left: 4px solid #34a853;
}

.recommendation-btn {
  width: 100%;
  padding: 0.75rem;
  margin-bottom: 1.25rem;
  background: linear-gradient(to right, #4285f4, #34a853);
  color: white;
  border: none;
  border-radius: 0.5rem;
  cursor: pointer;
  font-size: 1rem;
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 0.5rem;
  transition: transform 0.3s ease, box-shadow 0.3s ease;
}

.recommendation-btn:hover:not(:disabled) {
  transform: translateY(-2px);
  box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1);
}

.recommendation-btn:disabled {
  opacity: 0.7;
  cursor: not-allowed;
}

.recommendations-list {
  display: flex;
  flex-direction: column;
  gap: 1rem;
}

.recommendation-item {
  padding: 1rem;
  background: rgba(52, 168, 83, 0.05);
  border-radius: 0.5rem;
  border-left: 3px solid #34a853;
  line-height: 1.6;
}

.placeholder-content {
  padding: 2rem;
  text-align: center;
  color: #6c757d;
  background: rgba(0, 0, 0, 0.02);
  border-radius: 0.5rem;
}

/* Responsive Design */
@media (max-width: 768px) {
  .dashboard-container {
    padding: 1rem;
  }

  .dashboard-grid {
    grid-template-columns: 1fr;
  }

  .stats-grid {
    grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
  }

  .history-item, 
  .course-item {
    flex-direction: column;
    align-items: flex-start;
  }

  .history-data {
    margin-top: 0.75rem;
    width: 100%;
    justify-content: space-between;
  }
}
</style>