<template>
  <div :class="isDarkMode ? 'dark-mode' : 'light-mode'" class="dashboard-container">
    <div class="dashboard-content">
      <!-- Dashboard Header -->
      <header class="dashboard-header">
        <h1 class="dashboard-title">
          <span class="title-regular">Your</span>
          <span class="title-fancy">Academic Insights</span>
        </h1>
        <div class="header-actions">
          <button class="action-btn" @click="refreshData">
            <i class="fas fa-sync-alt me-2"></i> Refresh
          </button>
        </div>
      </header>

      <!-- Loading State -->
      <div v-if="loading" class="loading-container">
        <div class="loading-indicator" role="status">
          <span class="visually-hidden">Loading...</span>
        </div>
        <p>Analyzing your academic data...</p>
      </div>

      <!-- Error State -->
      <div v-if="error" class="alert-container">
        <div class="alert-message">
          <strong>Error:</strong> {{ error }}
        </div>
      </div>

      <!-- Dashboard Content -->
      <div v-if="!loading && !error" class="dashboard-main">
        <!-- Student Summary Stats -->
        <div class="stats-grid">
          <div class="stat-card">
            <h3>CGPA</h3>
            <p class="stat-value">{{ studentData?.cgpa || 'N/A' }}</p>
            <div class="progress">
              <div 
                class="progress-bar" 
                :class="gpaColorClass" 
                role="progressbar"
                :style="{ width: `${gpaPercentage}%` }"
                :aria-valuenow="gpaPercentage"
                aria-valuemin="0"
                aria-valuemax="100">
              </div>
            </div>
          </div>
          
          <div class="stat-card">
            <h3>Current Trimester</h3>
            <p class="stat-value">{{ studentData?.current_trimester || 'N/A' }}</p>
            <p class="stat-trend">ID: {{ studentData?.student_id || 'N/A' }}</p>
          </div>
          
          <div class="stat-card">
            <h3>Performance Trend</h3>
            <p class="stat-value">
              <span class="trend-badge" :class="trendClass">
                {{ performanceTrend }}
                <i :class="trendIcon"></i>
              </span>
            </p>
            <p class="stat-trend" :class="{'positive': trendClass === 'trend-up'}">
              {{ getTrendDescription() }}
            </p>
          </div>
          
          <div class="stat-card">
            <h3>Attendance</h3>
            <p class="stat-value">{{ calculateAverageAttendance() }}%</p>
            <div class="progress">
              <div 
                class="progress-bar" 
                :class="attendanceColorClass(calculateAverageAttendance())" 
                role="progressbar"
                :style="{ width: `${calculateAverageAttendance()}%` }"
                :aria-valuenow="calculateAverageAttendance()"
                aria-valuemin="0"
                aria-valuemax="100">
              </div>
            </div>
          </div>
        </div>

        <!-- AI-Generated Narrative Card -->
        <div class="dashboard-card narrative-card">
          <div class="card-header">
            <h2>
              <i class="fas fa-robot me-2"></i> Your Personalized Insights
            </h2>
            <span class="badge">Generated by Gemini</span>
          </div>
          <div class="card-body">
            <div v-if="narrative" class="narrative-content">
              <div v-for="(paragraph, index) in formattedNarrative" :key="index" class="narrative-paragraph">
                {{ paragraph }}
              </div>
            </div>
            <div v-else class="placeholder-content">
              <p>No narrative available. Try refreshing the data.</p>
            </div>
          </div>
        </div>

        <!-- Current Courses Card -->
        <div class="dashboard-card">
          <div class="card-header">
            <h2>
              <i class="fas fa-book-open me-2"></i> Current Courses
            </h2>
            <button class="action-btn-small">View All</button>
          </div>
          <div class="card-body">
            <div v-if="ongoingCourses.length" class="table-section">
              <div class="table-container">
                <table class="dashboard-table">
                  <thead>
                    <tr>
                      <th>Course</th>
                      <th>Code</th>
                      <th>Quiz 1</th>
                      <th>Quiz 2</th>
                      <th>Attendance</th>
                      <th>Progress</th>
                      <th>Actions</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr v-for="course in paginatedCourses" :key="course.course_code">
                      <td>{{ course.course_name }}</td>
                      <td>{{ course.course_code }}</td>
                      <td>{{ course.quiz1 ? course.quiz1.toFixed(1) : 'Pending' }}</td>
                      <td>{{ course.quiz2 ? course.quiz2.toFixed(1) : 'Pending' }}</td>
                      <td>
                        <span :class="attendanceColorTextClass(course.attendance_percentage)">
                          {{ course.attendance_percentage ? course.attendance_percentage.toFixed(1) + '%' : 'N/A' }}
                        </span>
                      </td>
                      <td>
                        <div class="progress">
                          <div 
                            class="progress-bar bg-primary" 
                            role="progressbar"
                            :style="{ width: `${calculateCourseProgress(course)}%` }"
                            :aria-valuenow="calculateCourseProgress(course)"
                            aria-valuemin="0"
                            aria-valuemax="100">
                          </div>
                        </div>
                        <small>{{ calculateCourseProgress(course) }}%</small>
                      </td>
                      <td>
                        <button class="action-btn-small" @click="viewCourseComparison(course.course_code)">
                          <i class="fas fa-chart-bar me-1"></i> Compare
                        </button>
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>
              
              <div class="pagination-controls" v-if="totalCoursePages > 1">
                <button 
                  class="pagination-btn" 
                  :disabled="coursesCurrentPage === 1"
                  @click="coursesCurrentPage--"
                >
                  <i class="fas fa-chevron-left"></i>
                </button>
                <span>Page {{ coursesCurrentPage }} of {{ totalCoursePages }}</span>
                <button 
                  class="pagination-btn" 
                  :disabled="coursesCurrentPage === totalCoursePages"
                  @click="coursesCurrentPage++"
                >
                  <i class="fas fa-chevron-right"></i>
                </button>
              </div>
            </div>
            <div v-else class="placeholder-content">
              <p>You are not currently enrolled in any courses.</p>
            </div>
          </div>
        </div>

        <!-- Performance History Card -->
        <div class="dashboard-card">
          <div class="card-header">
            <h2>
              <i class="fas fa-history me-2"></i> Performance History
            </h2>
            <button class="action-btn-small">View All</button>
          </div>
          <div class="card-body">
            <div v-if="completedCourses.length" class="table-section">
              <div class="table-container">
                <table class="dashboard-table">
                  <thead>
                    <tr>
                      <th>Course</th>
                      <th>Code</th>
                      <th>Trimester</th>
                      <th>Grade</th>
                      <th>Score</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr v-for="course in paginatedHistory" :key="course.course_code">
                      <td>{{ course.course_name }}</td>
                      <td>{{ course.course_code }}</td>
                      <td>
                        <div class="trimester-badge">{{ course.trimester }}</div>
                      </td>
                      <td>
                        <div class="grade-badge" :class="gradeColorClass(course.grade)">
                          {{ course.grade }}
                        </div>
                      </td>
                      <td>{{ course.total_score ? course.total_score.toFixed(1) : 'N/A' }}</td>
                    </tr>
                  </tbody>
                </table>
              </div>
              
              <div class="pagination-controls" v-if="totalHistoryPages > 1">
                <button 
                  class="pagination-btn" 
                  :disabled="historyCurrentPage === 1"
                  @click="historyCurrentPage--"
                >
                  <i class="fas fa-chevron-left"></i>
                </button>
                <span>Page {{ historyCurrentPage }} of {{ totalHistoryPages }}</span>
                <button 
                  class="pagination-btn" 
                  :disabled="historyCurrentPage === totalHistoryPages"
                  @click="historyCurrentPage++"
                >
                  <i class="fas fa-chevron-right"></i>
                </button>
              </div>
            </div>
            <div v-else class="placeholder-content">
              <p>You have not completed any courses yet.</p>
            </div>
          </div>
        </div>

        <!-- Course Recommendations Card -->
        <div class="dashboard-card recommendation-card">
          <div class="card-header">
            <h2>
              <i class="fas fa-lightbulb me-2"></i> Course Recommendations
            </h2>
          </div>
          <div class="card-body">
            <button class="action-btn" @click="fetchRecommendations" :disabled="loadingRecommendations">
              <i class="fas fa-magic me-2"></i>
              {{ loadingRecommendations ? 'Generating Recommendations...' : 'Get AI Recommendations' }}
            </button>
            
            <div v-if="recommendations" class="narrative-content mt-4">
              <div v-for="(paragraph, index) in formattedRecommendations" :key="index" class="narrative-paragraph">
                {{ paragraph }}
              </div>
            </div>
            <div v-else-if="!loadingRecommendations" class="placeholder-content">
              <p>Click the button above to get personalized course recommendations based on your performance.</p>
            </div>
          </div>
        </div>
      </div>
    </div>

    <footer class="dashboard-footer">
      Made with ❤️ by DevAstators
    </footer>
  </div>
</template>

<script>
import axios from 'axios';

export default {
  name: 'StudentInsightsDashboard',
  data() {
    return {
      studentData: {},
      narrative: '',
      recommendations: null,
      loading: true,
      loadingRecommendations: false,
      error: null,
      authToken: null,
      isDarkMode: false,
      coursesCurrentPage: 1,
      historyCurrentPage: 1,
      itemsPerPage: 5
    };
  },
  computed: {
    // Transform courses object into arrays
    ongoingCourses() {
      if (!this.studentData?.courses) return [];
      
      // Filter for ongoing courses (those without a grade)
      return Object.values(this.studentData.courses).filter(course => 
        course.status === 'Ongoing' || !course.grade
      );
    },
    
    completedCourses() {
      if (!this.studentData?.courses) return [];
      
      // Filter for completed courses (those with a grade)
      return Object.values(this.studentData.courses).filter(course => 
        course.status === 'Completed' || course.grade
      );
    },
    
    formattedNarrative() {
      if (!this.narrative) return [];
      return this.narrative.split('\n\n').filter(p => p.trim());
    },
    
    formattedRecommendations() {
      if (!this.recommendations) return [];
      return this.recommendations.split('\n\n').filter(p => p.trim());
    },
    
    gpaPercentage() {
      const cgpa = this.studentData?.cgpa || 0;
      return (cgpa / 10) * 100;
    },
    
    gpaColorClass() {
      const cgpa = this.studentData?.cgpa || 0;
      if (cgpa >= 8) return 'bg-success';
      if (cgpa >= 6) return 'bg-warning';
      return 'bg-danger';
    },
    
    trendClass() {
      const trend = this.studentData?.performance_trend || '';
      if (trend?.toLowerCase() === 'improving') return 'trend-up';
      if (trend?.toLowerCase() === 'declining') return 'trend-down';
      return 'trend-stable';
    },
    
    trendIcon() {
      const trend = this.studentData?.performance_trend || '';
      if (trend?.toLowerCase() === 'improving') return 'fas fa-arrow-up';
      if (trend?.toLowerCase() === 'declining') return 'fas fa-arrow-down';
      return 'fas fa-equals';
    },
    
    paginatedCourses() {
      const start = (this.coursesCurrentPage - 1) * this.itemsPerPage;
      return this.ongoingCourses.slice(start, start + this.itemsPerPage);
    },
    
    totalCoursePages() {
      return Math.ceil(this.ongoingCourses.length / this.itemsPerPage) || 1;
    },
    
    paginatedHistory() {
      const start = (this.historyCurrentPage - 1) * this.itemsPerPage;
      return this.completedCourses.slice(start, start + this.itemsPerPage);
    },
    
    totalHistoryPages() {
      return Math.ceil(this.completedCourses.length / this.itemsPerPage) || 1;
    },
    
    // Get performance trend based on grades or create a default one
    performanceTrend() {
      if (this.studentData?.performance_trend) {
        return this.studentData.performance_trend;
      }
      
      // If no trend is provided, we can calculate a simple one
      if (this.completedCourses.length >= 2) {
        const sortedCourses = [...this.completedCourses].sort((a, b) => {
          const trimA = parseInt(a.trimester.replace('Trimester ', ''));
          const trimB = parseInt(b.trimester.replace('Trimester ', ''));
          return trimB - trimA; // Sort by most recent first
        });
        
        // Compare latest two trimesters
        if (sortedCourses.length >= 2) {
          const latest = sortedCourses[0].total_score;
          const previous = sortedCourses[1].total_score;
          
          if (latest > previous + 5) return 'Improving';
          if (latest < previous - 5) return 'Declining';
          return 'Stable';
        }
      }
      
      return 'Stable';
    }
  },
  created() {
    this.initializeAuth();
    // Check system preference for dark mode
    this.isDarkMode = window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches;
    this.checkAuthentication();
  },
  mounted() {
    this.fetchInsights();
    
    // Add listener for system dark mode changes
    const darkModeMediaQuery = window.matchMedia('(prefers-color-scheme: dark)');
    if (darkModeMediaQuery.addEventListener) {
      darkModeMediaQuery.addEventListener('change', e => {
        this.isDarkMode = e.matches;
      });
    } else {
      // Fallback for older browsers
      darkModeMediaQuery.addListener(e => {
        this.isDarkMode = e.matches;
      });
    }
  },
  methods: {
    initializeAuth() {
      this.authToken = localStorage.getItem('authToken');
      if (!this.authToken) {
        this.error = 'Please login to access your insights';
        this.loading = false;
        if (this.$router) {
          this.$router.push('/login');
        }
      }
    },

    getAuthToken() {
  // Retrieve the JWT token from localStorage
    return localStorage.getItem('authToken');
  },

    checkAuthentication() {
      const token = this.getAuthToken();
      if (!token) {
        this.$router.push('/signin');
      }
    },
    
    async fetchInsights() {
  if (!this.authToken) return;
  
  this.loading = true;
  this.error = null;
  
  try {
    const response = await axios.get('http://127.0.0.1:3000/api/student/insights', {
      headers: {
        'Authorization': this.authToken,
        'Content-Type': 'application/json'
      }
    });
    
    // Handle case where response might be a string
    let data = response.data;
    if (typeof data === 'string') {
      try {
        data = JSON.parse(data);
      } catch (parseError) {
        console.error('Error parsing response data:', parseError);
        throw new Error('Invalid data format received from server');
      }
    }
    
    console.log('Processed data:', data);
    
    // Extract student data from the correct structure
    if (data && data.student_data) {
      this.studentData = data.student_data;
      this.narrative = data.narrative || '';
    } else if (data) {
      this.studentData = data;
      this.narrative = ''; 
    } else {
      throw new Error('No data received from the server');
    }
    
    // Reset pagination
    this.coursesCurrentPage = 1;
    this.historyCurrentPage = 1;
  } catch (error) {
    console.error('Error fetching insights:', error);
    
    if (error.response) {
      console.error('Response status:', error.response.status);
      console.error('Response data:', error.response.data);
    }
    
    this.error = error.response?.data?.message || 
                'Failed to load your academic insights. Please try again.';
  } finally {
    this.loading = false;
  }
},
    
    async fetchRecommendations() {
      if (!this.authToken) return;
      
      this.loadingRecommendations = true;
      
      try {
        const response = await axios.get('http://127.0.0.1:3000/api/student/recommendations', {
          headers: {
            'Authorization': this.authToken,
            'Content-Type': 'application/json'
          }
        });
        
        this.recommendations = response.data.recommendations || '';
      } catch (error) {
        console.error('Error fetching recommendations:', error);
        const errorMessage = error.response?.data?.message || 
                           'Failed to load recommendations. Please try again.';
        
        // Simple alert if no toast system
        alert(errorMessage);
      } finally {
        this.loadingRecommendations = false;
      }
    },
    
    refreshData() {
      this.fetchInsights();
      this.recommendations = null;
    },
    
    viewCourseComparison(courseCode) {
      // Remove non-numeric characters for route
      const courseId = courseCode.replace(/[^0-9]/g, '');
      if (this.$router) {
        this.$router.push(`/student/courses/${courseId}/comparison`);
      } else {
        window.location.href = `/student/courses/${courseId}/comparison`;
      }
    },
    
    calculateCourseProgress(course) {
      // Simplified progress calculation
      if (!course) return 0;
      if (course.endterm) return 100;
      if (course.quiz2) return 90;
      if (course.assignment6) return 75;
      if (course.quiz1) return 50;
      if (course.assignment1) return 25;
      return 10; // Course started but no assessments yet
    },
    
    attendanceColorClass(percentage) {
      if (!percentage) return '';
      if (percentage < 75) return 'bg-danger';
      if (percentage < 85) return 'bg-warning';
      return 'bg-success';
    },
    
    attendanceColorTextClass(percentage) {
      if (!percentage) return '';
      if (percentage < 75) return 'text-danger';
      if (percentage < 85) return 'text-warning';
      return 'text-success';
    },
    
    gradeColorClass(grade) {
      if (!grade) return '';
      if (grade === 'A') return 'grade-a';
      if (grade === 'B') return 'grade-b';
      if (grade === 'C') return 'grade-c';
      if (grade === 'D') return 'grade-d';
      return 'grade-f';
    },

    calculateAverageAttendance() {
      if (!this.ongoingCourses.length) return 0;
      
      const totalAttendance = this.ongoingCourses.reduce((sum, course) => {
        return sum + (course.attendance_percentage || 0);
      }, 0);
      
      return Math.round(totalAttendance / this.ongoingCourses.length);
    },
    
    getTrendDescription() {
      const trend = this.performanceTrend;
      if (trend.toLowerCase() === 'improving') return 'Keep up the good work!';
      if (trend.toLowerCase() === 'declining') return 'Needs attention';
      return 'Maintaining consistent performance';
    }
  }
};
</script>

<style scoped>
.dashboard-container {
  min-height: 100vh;
  padding: 2rem;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
}

/* Theme Variables */
.dark-mode {
  --background: #121212;
  --card-bg: rgba(255, 255, 255, 0.05);
  --card-border: rgba(255, 255, 255, 0.1);
  --text: #e1e1e1;
  --text-secondary: #a0a0a0;
  --primary: rgb(99, 102, 241);
  --primary-gradient: linear-gradient(to right, rgb(99, 102, 241), rgb(168, 85, 247));
  --danger: #ef4444;
  --warning: #f59e0b;
  --success: #10b981;
  --item-bg: rgba(255, 255, 255, 0.03);
  background-color: var(--background);
  color: var(--text);
}

.light-mode {
  --background: #f5f5f7;
  --card-bg: rgba(255, 255, 255, 0.9);
  --card-border: rgba(0, 0, 0, 0.1);
  --text: #333333;
  --text-secondary: #666666;
  --primary: rgb(99, 102, 241);
  --primary-gradient: linear-gradient(to right, rgb(99, 102, 241), rgb(168, 85, 247));
  --danger: #ef4444;
  --warning: #f59e0b;
  --success: #10b981;
  --item-bg: rgba(0, 0, 0, 0.03);
  background-color: var(--background);
  color: var(--text);
}

.dashboard-content {
  position: relative;
  z-index: 10;
  max-width: 1280px;
  margin: 0 auto;
}

/* Dashboard Header */
.dashboard-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 2rem;
}

.dashboard-title {
  font-size: clamp(1.5rem, 4vw, 2.5rem);
  margin-bottom: 0.5rem;
}

.title-regular {
  color: var(--text);
}

.title-fancy {
  font-family: 'Pacifico', cursive;
  background: var(--primary-gradient);
  -webkit-background-clip: text;
  color: transparent;
  margin-left: 0.5rem;
}

/* Loading Container */
.loading-container {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  padding: 50px 0;
}

.loading-indicator {
  width: 3rem;
  height: 3rem;
  border: 0.25rem solid rgba(255, 255, 255, 0.1);
  border-radius: 50%;
  border-top-color: var(--primary);
  animation: spin 1s linear infinite;
  margin-bottom: 1rem;
}

.visually-hidden {
  position: absolute;
  width: 1px;
  height: 1px;
  padding: 0;
  margin: -1px;
  overflow: hidden;
  clip: rect(0, 0, 0, 0);
  white-space: nowrap;
  border: 0;
}

/* Alert Container */
.alert-container {
  margin-bottom: 2rem;
}

.alert-message {
  padding: 1rem;
  background-color: rgba(239, 68, 68, 0.2);
  border-radius: 0.5rem;
  color: var(--danger);
}

/* Stats Grid */
.stats-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(240px, 1fr));
  gap: 1rem;
  margin-bottom: 2rem;
}

.stat-card {
  background: var(--card-bg);
  backdrop-filter: blur(10px);
  padding: 1.5rem;
  border-radius: 1rem;
  border: 1px solid var(--card-border);
  transition: transform 0.2s, box-shadow 0.3s;
}

.stat-card:hover {
  transform: translateY(-5px);
  box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
}

.stat-value {
  font-size: 2rem;
  font-weight: bold;
  margin: 0.5rem 0;
  background: var(--primary-gradient);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
}

.stat-trend {
  font-size: 0.9rem;
  color: var(--text-secondary);
}

.stat-trend.positive {
  color: var(--success);
}

/* Dashboard Cards */
.dashboard-main {
  display: flex;
  flex-direction: column;
  gap: 2rem;
}

.dashboard-card {
  background: var(--card-bg);
  backdrop-filter: blur(10px);
  padding: 1.5rem;
  border-radius: 1rem;
  border: 1px solid var(--card-border);
  transition: transform 0.2s, box-shadow 0.3s;
}

.dashboard-card:hover {
  transform: translateY(-2px);
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
}

.dashboard-card:nth-child(3) {
  background: linear-gradient(135deg, rgba(99, 102, 241, 0.05), rgba(168, 85, 247, 0.05));
}

.dashboard-card:nth-child(4) {
  background: linear-gradient(135deg, rgba(236, 72, 153, 0.05), rgba(239, 68, 68, 0.05));
}

.dashboard-card:nth-child(5) {
  background: linear-gradient(135deg, rgba(16, 185, 129, 0.05), rgba(5, 150, 105, 0.05));
}

.card-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 1.5rem;
}

.card-header h2 {
  font-size: 1.5rem;
  margin: 0;
  display: flex;
  align-items: center;
}

.card-header h2 i {
  margin-right: 0.5rem;
}

.badge {
  padding: 0.25rem 0.75rem;
  background: var(--primary-gradient);
  color: white;
  border-radius: 1rem;
  font-size: 0.8rem;
}

.narrative-card {
  border-left: 4px solid var(--primary);
  background: linear-gradient(135deg, rgba(56, 189, 248, 0.1), rgba(14, 165, 233, 0.1));
}

.narrative-content {
  line-height: 1.6;
}

.narrative-paragraph {
  margin-bottom: 15px;
}

.placeholder-content {
  padding: 1.5rem;
  text-align: center;
  color: var(--text-secondary);
}

/* Table Section */
.table-section {
  display: flex;
  flex-direction: column;
  gap: 1.5rem;
}

.table-container {
  max-height: 400px;
  overflow-y: auto;
  border-radius: 0.5rem;
  border: 1px solid var(--card-border);
}

/* Tables */
.dashboard-table {
  width: 100%;
  border-collapse: collapse;
}

.dashboard-table th,
.dashboard-table td {
  padding: 1rem;
  text-align: left;
  border-bottom: 1px solid var(--card-border);
}

.dashboard-table th {
  position: sticky;
  top: 0;
  background: rgba(0, 0, 0, 0.2);
  font-weight: bold;
  color: var(--text-secondary);
  z-index: 10;
}

.dashboard-table tr:hover {
  background: var(--item-bg);
}

/* Pagination Controls */
.pagination-controls {
  display: flex;
  justify-content: center;
  align-items: center;
  gap: 1rem;
  margin: 0.5rem 0;
}

.pagination-btn {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 2rem;
  height: 2rem;
  border-radius: 50%;
  border: none;
  background-color: var(--item-bg);
  color: var(--text);
  cursor: pointer;
  transition: all 0.2s;
}

.pagination-btn:hover {
  background: var(--primary-gradient);
  color: white;
  transform: translateY(-1px);
}

.pagination-btn:disabled {
  opacity: 0.5;
  cursor: not-allowed;
  transform: none;
}

/* Progress */
.progress {
  height: 8px;
  background-color: var(--item-bg);
  border-radius: 4px;
  overflow: hidden;
  margin-top: 0.5rem;
}

.progress-bar {
  height: 100%;
  border-radius: 4px;
  transition: width 0.3s ease;
}

.bg-primary {
  background-color: var(--primary);
}

.bg-danger {
  background-color: var(--danger);
}

.bg-warning {
  background-color: var(--warning);
}

.bg-success {
  background-color: var(--success);
}

/* Text Colors */
.text-danger {
  color: var(--danger);
}

.text-warning {
  color: var(--warning);
}

.text-success {
  color: var(--success);
}

/* Badges */
.trend-badge, .trimester-badge, .grade-badge {
  display: inline-block;
  padding: 0.25rem 0.5rem;
  border-radius: 0.5rem;
  font-size: 0.9rem;
  border: 1px solid rgba(255, 255, 255, 0.1);
  transition: transform 0.2s;
}

.trend-badge:hover, .trimester-badge:hover, .grade-badge:hover {
  transform: translateY(-1px);
}

.trend-up {
  background-color: rgba(16, 185, 129, 0.2);
  color: var(--success);
}

.trend-down {
  background-color: rgba(239, 68, 68, 0.2);
  color: var(--danger);
}

.trend-stable {
  background-color: rgba(160, 160, 160, 0.2);
  color: var(--text);
}

.trimester-badge {
  background-color: var(--item-bg);
  color: var(--text);
}

.grade-a {
  background-color: rgba(16, 185, 129, 0.2);
  color: var(--success);
}

.grade-b {
  background-color: rgba(99, 102, 241, 0.2);
  color: var(--primary);
}

.grade-c {
  background-color: rgba(245, 158, 11, 0.2);
  color: var(--warning);
}

.grade-d, .grade-f {
  background-color: rgba(239, 68, 68, 0.2);
  color: var(--danger);
}

/* Buttons */
.action-btn {
  display: flex;
  align-items: center;
  padding: 0.5rem 1rem;
  background: var(--primary-gradient);
  color: white;
  border: none;
  border-radius: 0.5rem;
  font-weight: 500;
  cursor: pointer;
  transition: all 0.2s ease;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
}

.action-btn:hover {
  transform: translateY(-2px);
  box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
  opacity: 0.9;
}

.action-btn:disabled {
  opacity: 0.7;
  cursor: not-allowed;
  transform: none;
}

.action-btn-small {
  padding: 0.375rem 0.75rem;
  font-size: 0.875rem;
  background: rgba(99, 102, 241, 0.2);
  color: var(--primary);
  border: none;
  border-radius: 0.5rem;
  cursor: pointer;
  transition: all 0.2s ease;
}

.action-btn-small:hover {
  background: rgba(99, 102, 241, 0.3);
  transform: translateY(-1px);
}

/* Recommendation Card Styles */
.recommendation-card {
  border-left: 4px solid var(--warning);
  background: linear-gradient(135deg, rgba(245, 158, 11, 0.05), rgba(249, 115, 22, 0.05));
}

/* Footer Styles */
.dashboard-footer {
  text-align: center;
  margin-top: 3rem;
  padding: 1.5rem;
  color: var(--text-secondary);
  font-size: 0.9rem;
  border-top: 1px solid var(--card-border);
}

/* Animations */
@keyframes spin {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}

/* Scrollbar Styling */
.table-container::-webkit-scrollbar {
  width: 8px;
  height: 8px;
}

.table-container::-webkit-scrollbar-track {
  background: var(--item-bg);
  border-radius: 4px;
}

.table-container::-webkit-scrollbar-thumb {
  background: var(--text-secondary);
  border-radius: 4px;
}

.table-container::-webkit-scrollbar-thumb:hover {
  background: var(--primary);
}

/* Empty State Styling */
.empty-state {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  padding: 2rem;
  text-align: center;
  background: var(--item-bg);
  border-radius: 0.5rem;
  min-height: 150px;
}

.empty-icon, .empty-state-icon {
  font-size: 2.5rem;
  margin-bottom: 1rem;
  opacity: 0.7;
}

.empty-state p, .empty-state-message {
  margin: 0 0 0.5rem 0;
  font-size: 1rem;
  color: var(--text-secondary);
}

/* Utility classes */
.me-1 {
  margin-right: 0.25rem;
}

.me-2 {
  margin-right: 0.5rem;
}

.mt-4 {
  margin-top: 1rem;
}

/* Responsive Adjustments */
@media (max-width: 768px) {
  .dashboard-container {
    padding: 1rem;
  }
  
  .dashboard-header {
    flex-direction: column;
    align-items: flex-start;
    gap: 1rem;
  }
  
  .header-actions {
    width: 100%;
  }
  
  .stats-grid {
    grid-template-columns: 1fr;
  }
  
  .card-header {
    flex-direction: column;
    align-items: flex-start;
    gap: 0.5rem;
  }
  
  .table-container {
    overflow-x: auto;
  }
  
  .dashboard-table th,
  .dashboard-table td {
    padding: 0.75rem 0.5rem;
    font-size: 0.9rem;
  }
}

/* Light Mode Adjustments */
.light-mode .dashboard-table th {
  background: rgba(240, 240, 240, 0.9);
  color: var(--text-secondary);
}

.light-mode .progress {
  background-color: rgba(0, 0, 0, 0.1);
}

.light-mode .dashboard-table tr:hover {
  background-color: rgba(99, 102, 241, 0.05);
}

.dark-mode .dashboard-table tr:hover {
  background-color: rgba(99, 102, 241, 0.1);
}

/* Accessibility Enhancements */
:focus {
  outline: 2px solid var(--primary);
  outline-offset: 2px;
}

.visually-hidden:not(:focus):not(:active) {
  clip: rect(0 0 0 0);
  clip-path: inset(50%);
  height: 1px;
  overflow: hidden;
  position: absolute;
  white-space: nowrap;
  width: 1px;
}

/* Course Progress Custom Styling */
.course-progress-label {
  display: flex;
  justify-content: space-between;
  font-size: 0.8rem;
  margin-top: 0.25rem;
}

/* Skeleton Loading Animation */
@keyframes pulse {
  0% { opacity: 0.6; }
  50% { opacity: 0.8; }
  100% { opacity: 0.6; }
}

.skeleton-loading {
  animation: pulse 1.5s infinite;
  background: var(--item-bg);
  border-radius: 4px;
}
</style>